# -*- coding: utf-8 -*-
"""Тематические диалоги с голосовым ответом и слотами вариативности.

Слоты: dialog["slots"] = {имя: [вариант, ...]}; вариант — dict со строковыми полями.
В строках шаблонов {имя.поле} подставляется при каждом запуске диалога (случайный выбор).
Поле key каждого варианта используется в keys для проверки ответа.
"""

DIALOGS = [

 # ---------- КАФЕ (слоты: напиток, сладкое) ----------
 dict(id="cafe", unit=3, title="В кафе", icon="☕",
  brief="Вы в кафе. Закажите {bebida.ru} и {doce.ru}, попросите счёт.",
  slots=dict(
    bebida=[
      dict(pt="um café", ru="кофе", key="café"),
      dict(pt="um chá", ru="чай", key="chá"),
      dict(pt="um sumo de laranja", ru="апельсиновый сок", key="sumo"),
      dict(pt="um galão", ru="галан (кофе с молоком)", key="galão"),
    ],
    doce=[
      dict(pt="um pastel de nata", ru="паштел де ната", key="pastel"),
      dict(pt="um bolo de chocolate", ru="кусок шоколадного торта", key="bolo"),
      dict(pt="uma sandes de queijo", ru="сэндвич с сыром", key="sandes"),
    ]),
  steps=[
   dict(say="Bom dia! Faz favor.", ru="Доброе утро! Слушаю вас.",
        task="Поздоровайтесь и закажите {bebida.ru}.",
        model="Bom dia! {bebida.pt}, por favor.",
        models=["Olá! Queria {bebida.pt}, por favor."],
        keys=[["bom dia","boa tarde","olá"],["{bebida.key}"],["por favor","faz favor","queria","quero"]]),
   dict(say="Com certeza. Mais alguma coisa?", ru="Конечно. Что-нибудь ещё?",
        task="Да — попросите ещё {doce.ru}.",
        model="Sim, {doce.pt}, por favor.",
        models=["Queria também {doce.pt}."],
        keys=[["{doce.key}"]]),
   dict(say="Aqui está. Bom apetite!", ru="Вот, пожалуйста. Приятного аппетита!",
        task="Поблагодарите и попросите счёт.",
        model="Obrigada! A conta, por favor.",
        models=["Muito obrigada! Pode trazer a conta?", "Obrigada. Quanto é?"],
        keys=[["obrigad"],["conta","quanto"]]),
   dict(say="São três euros e cinquenta. Até logo!", ru="Три евро пятьдесят. До скорого!",
        task="Попрощайтесь.",
        model="Até logo!",
        models=["Adeus!", "Obrigada, até logo!", "Até amanhã!"],
        keys=[["até logo","adeus","até amanhã","bom dia","obrigada"]]),
  ]),

 # ---------- РЕСТОРАН (столик → блюдо дня → сколько ждать → счёт и с собой) ----------
 dict(id="restaurante", unit=3, title="В ресторане", icon="🍽",
  brief="Попросите столик {mesa.ru}, закажите блюдо дня и {bebida.ru}, узнайте, сколько ждать, и попросите завернуть остатки с собой.",
  slots=dict(
    mesa=[
      dict(pt="junto à janela", ru="у окна", key="janela"),
      dict(pt="na esplanada", ru="на террасе", key="esplanada"),
      dict(pt="para duas pessoas", ru="на двоих", key="duas"),
    ],
    prato=[
      dict(pt="bacalhau com batatas", key="bacalhau"),
      dict(pt="frango com arroz", key="frango"),
      dict(pt="sardinhas com salada", key="sardinhas"),
      dict(pt="bife com massa", key="bife"),
    ],
    bebida=[
      dict(pt="um copo de vinho tinto", ru="бокал красного вина", key="tinto"),
      dict(pt="um copo de vinho branco", ru="бокал белого вина", key="branco"),
      dict(pt="uma água", ru="воду", key="água"),
      dict(pt="um sumo de laranja", ru="апельсиновый сок", key="sumo"),
    ]),
  steps=[
   dict(say="Boa noite! Bem-vindos!", ru="Добрый вечер! Добро пожаловать!",
        task="Спросите, есть ли свободный столик {mesa.ru}.",
        model="Boa noite! Tem uma mesa livre {mesa.pt}?",
        models=["Tem uma mesa {mesa.pt}?", "Há uma mesa livre {mesa.pt}?"],
        keys=[["mesa"],["{mesa.key}"]]),
   dict(say="Temos, sim. Aqui está a ementa. Hoje, o prato do dia é {prato.pt}.",
        ru="Есть. Вот меню. Сегодня блюдо дня — {prato.pt}.",
        task="Закажите блюдо дня и {bebida.ru}.",
        model="Queria o prato do dia e {bebida.pt}, por favor.",
        models=["Para mim, o {prato.key} e {bebida.pt}.", "O prato do dia e {bebida.pt}, por favor."],
        keys=[["prato do dia","{prato.key}"],["{bebida.key}"]]),
   dict(say="Com certeza. Boa escolha!", ru="Конечно. Отличный выбор!",
        task="Спросите, сколько времени займёт приготовление.",
        model="Quanto tempo demora?",
        models=["Demora muito tempo?", "Quanto tempo é que demora?"],
        keys=[["demora","tempo"]]),
   dict(say="Demora quinze minutos. Vou já trazer a bebida.", ru="Пятнадцать минут. Сейчас принесу напиток.",
        task="Поблагодарите.",
        model="Obrigada!",
        models=["Muito obrigada!", "Está bem, obrigada."],
        keys=[["obrigad","está bem"]]),
   dict(say="Foi tudo do seu agrado?", ru="Вам всё понравилось?",
        task="Скажите, что всё было очень вкусно, попросите счёт и завернуть остатки с собой.",
        model="Foi tudo muito bom! A conta, por favor. E posso levar o resto?",
        models=["Sim, gostei muito. A conta, por favor. Queria levar o resto.",
                "Muito bom! A conta, e o resto é para levar, por favor."],
        keys=[["muito bom","gostei"],["conta"],["levar"]]),
  ]),

 # ---------- РЫНОК (2 продукта, количество, пакет, где купить третье) ----------
 dict(id="mercado", unit=3, title="На рынке", icon="🥕",
  brief="Купите {prod1.ru} ({qtd.ru}) и {prod2.ru}, ответьте про пакет и узнайте, где купить {loja.prodRu}.",
  slots=dict(
    prod1=[
      dict(pt="tomate", ru="помидоры", key="tomate"),
      dict(pt="cebola", ru="лук", key="cebola"),
      dict(pt="batata", ru="картошку", key="batata"),
      dict(pt="cenoura", ru="морковь", key="cenoura"),
      dict(pt="laranja", ru="апельсины", key="laranja"),
    ],
    qtd=[
      dict(pt="um quilo", ru="килограмм", key="um quilo"),
      dict(pt="meio quilo", ru="полкило", key="meio quilo"),
      dict(pt="dois quilos", ru="два килограмма", key="dois quilos"),
    ],
    prod2=[
      dict(pt="queijo", ru="сыр", key="queijo"),
      dict(pt="fiambre", ru="ветчину", key="fiambre"),
      dict(pt="ovos", ru="яйца", key="ovos"),
      dict(pt="fruta", ru="фрукты", key="fruta"),
    ],
    saco=[
      dict(pt="Sim, por favor.", ru="да", key="sim"),
      dict(pt="Não, obrigada. Não é preciso.", ru="нет", key="não"),
    ],
    loja=[
      dict(prodPt="peixe fresco", prodRu="свежую рыбу", lojaPt="na peixaria", key="peixe"),
      dict(prodPt="pão", prodRu="хлеб", lojaPt="na padaria", key="pão"),
      dict(prodPt="carne", prodRu="мясо", lojaPt="no talho", key="carne"),
    ]),
  steps=[
   dict(say="Bom dia! O que deseja?", ru="Доброе утро! Что желаете?",
        task="Попросите {qtd.ru} — {prod1.ru}.",
        model="Bom dia! {qtd.pt} de {prod1.pt}, por favor.",
        models=["Queria {qtd.pt} de {prod1.pt}."],
        keys=[["{qtd.key}"],["{prod1.key}"]]),
   dict(say="Com certeza. Mais alguma coisa?", ru="Конечно. Ещё что-нибудь?",
        task="Да — спросите, есть ли у них {prod2.ru}.",
        model="Sim, tem {prod2.pt}?",
        models=["Tem {prod2.pt}?", "Sim, queria {prod2.pt}. Tem?"],
        keys=[["{prod2.key}"]]),
   dict(say="Temos, sim, muito bom. Precisa de um saco?", ru="Есть, очень хороший. Пакет нужен?",
        task="Ответьте: {saco.ru}.",
        model="{saco.pt}",
        models=["{saco.pt}"],
        keys=[["{saco.key}"]]),
   dict(say="Aqui está. Mais alguma coisa?", ru="Вот, пожалуйста. Что-то ещё?",
        task="Спросите, где можно купить {loja.prodRu}.",
        model="Onde posso comprar {loja.prodPt}?",
        models=["Onde é que posso comprar {loja.prodPt}?", "Sabe onde posso comprar {loja.prodPt}?"],
        keys=[["onde"],["{loja.key}"]]),
   dict(say="Pode comprar {loja.lojaPt}, ao lado do mercado.", ru="Можно купить {loja.lojaPt}, рядом с рынком.",
        task="Поблагодарите и попрощайтесь.",
        model="Muito obrigada! Bom dia!",
        models=["Obrigada! Adeus!", "Obrigada, até logo!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- СУПЕРМАРКЕТ (новый: где находится продукт) ----------
 dict(id="supermercado", unit=4, title="В супермаркете", icon="🛒",
  brief="Вы не находите {prod.ru}. Спросите, где это, и уточните про {prod2.ru}.",
  slots=dict(
    prod=[
      dict(pt="o leite", ru="молоко", loc="O leite está ao lado dos iogurtes.", key="leite"),
      dict(pt="o arroz", ru="рис", loc="O arroz está ao lado da massa.", key="arroz"),
      dict(pt="a manteiga", ru="сливочное масло", loc="A manteiga está ao lado do queijo.", key="manteiga"),
      dict(pt="o café", ru="кофе", loc="O café está em frente do chá.", key="café"),
      dict(pt="o azeite", ru="оливковое масло", loc="O azeite está na segunda secção, ao lado do sal.", key="azeite"),
    ],
    prod2=[
      dict(pt="ovos", ru="яйца", key="ovos"),
      dict(pt="pão fresco", ru="свежий хлеб", key="pão"),
      dict(pt="iogurtes", ru="йогурты", key="iogurte"),
    ]),
  steps=[
   dict(say="Boa tarde! Precisa de ajuda?", ru="Добрый день! Вам помочь?",
        task="Да — спросите, где находится {prod.ru}.",
        model="Sim, por favor. Onde está {prod.pt}?",
        models=["Onde fica {prod.pt}?", "Não encontro {prod.pt}. Onde está?"],
        keys=[["onde"],["{prod.key}"]]),
   dict(say="{prod.loc}", ru="{prod.loc}",
        task="Поблагодарите и спросите, есть ли у них {prod2.ru}.",
        model="Obrigada! E têm {prod2.pt}?",
        models=["Obrigada. Tem {prod2.pt}?"],
        keys=[["{prod2.key}"]]),
   dict(say="Temos, sim. Ficam ao lado da entrada.", ru="Есть. Они рядом со входом.",
        task="Поблагодарите за помощь.",
        model="Muito obrigada pela ajuda!",
        models=["Obrigada!", "Muito obrigada!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- АПТЕКА (что болит + симптом) ----------
 dict(id="farmacia", unit=6, title="В аптеке", icon="💊",
  brief="У вас {ail.ru} и {sin.ru}. Купите лекарство и спросите цену.",
  slots=dict(
    ail=[
      dict(frase="Dói-me a cabeça", ru="болит голова", key="cabeça"),
      dict(frase="Dói-me o joelho", ru="болит колено", key="joelho"),
      dict(frase="Dói-me o ouvido", ru="болит ухо", key="ouvido"),
      dict(frase="Dói-me a garganta", ru="болит горло", key="garganta"),
      dict(frase="Dói-me a barriga", ru="болит живот", key="barriga"),
      dict(frase="Doem-me as costas", ru="болит спина", key="costas"),
      dict(frase="Doem-me os dentes", ru="болят зубы", key="dente"),
    ],
    sin=[
      dict(frase="tenho tosse", ru="кашель", key="tosse"),
      dict(frase="tenho febre", ru="температура", key="febre"),
      dict(frase="estou com gripe", ru="грипп", key="gripe"),
      dict(frase="tenho insónias", ru="бессонница", key="insóni"),
    ]),
  steps=[
   dict(say="Boa tarde! Em que posso ajudar?", ru="Добрый день! Чем могу помочь?",
        task="Скажите: у вас {ail.ru}, и попросите обезболивающее.",
        model="Boa tarde! {ail.frase}. Queria um analgésico, por favor.",
        models=["{ail.frase}. Tem um analgésico?"],
        keys=[["{ail.key}"],["analgésico","comprimido","medicamento"]]),
   dict(say="Claro. Este é muito bom. Mais alguma coisa?", ru="Конечно. Вот это очень хорошее. Что-то ещё?",
        task="Да — скажите, что у вас ещё {sin.ru}, и спросите, что они рекомендуют.",
        model="Sim, {sin.frase}. O que recomenda?",
        models=["Também {sin.frase}. O que me recomenda?"],
        keys=[["{sin.key}"]]),
   dict(say="Tome este medicamento duas vezes por dia.", ru="Принимайте это лекарство два раза в день.",
        task="Спросите, сколько это стоит.",
        model="Quanto custa?",
        models=["Quanto é?", "Quanto custa tudo?"],
        keys=[["quanto custa","quanto é","quanto e"]]),
   dict(say="São nove euros e dez.", ru="Девять евро десять.",
        task="Поблагодарите и попрощайтесь.",
        model="Obrigada! Boa tarde!",
        models=["Muito obrigada! Adeus!", "Obrigada, até logo!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- ВРАЧ (симптомы-слоты) ----------
 dict(id="medico", unit=6, title="У врача", icon="🩺",
  brief="Вы на приёме: чувствуете себя плохо, {sono.ru}, {dor.ru}.",
  slots=dict(
    sono=[
      dict(frase="durmo mal e tenho insónias", ru="плохо спите", key="durmo"),
      dict(frase="estou sempre cansada", ru="всё время усталая", key="cansad"),
      dict(frase="acordo muitas vezes durante a noite", ru="часто просыпаетесь ночью", key="acordo"),
    ],
    dor=[
      dict(frase="doem-me as costas", ru="болит спина", key="costas"),
      dict(frase="dói-me a cabeça", ru="болит голова", key="cabeça"),
      dict(frase="dói-me a barriga", ru="болит живот", key="barriga"),
      dict(frase="dói-me o joelho", ru="болит колено", key="joelho"),
    ]),
  steps=[
   dict(say="Bom dia! Como se sente?", ru="Доброе утро! Как вы себя чувствуете?",
        task="Скажите, что чувствуете себя плохо.",
        model="Sinto-me mal, doutora.",
        models=["Não me sinto bem.", "Sinto-me mal."],
        keys=[["sinto","mal","não me sinto"]]),
   dict(say="E dorme bem?", ru="А спите хорошо?",
        task="Скажите: {sono.ru}.",
        model="Não. Eu {sono.frase}.",
        models=["{sono.frase}."],
        keys=[["{sono.key}"]]),
   dict(say="Tem dores?", ru="Боли есть?",
        task="Да — скажите: {dor.ru}.",
        model="Sim, {dor.frase}.",
        models=["{dor.frase}."],
        keys=[["{dor.key}"]]),
   dict(say="Vamos fazer análises. Durma mais e beba muita água.",
        ru="Сделаем анализы. Спите больше и пейте много воды.",
        task="Поблагодарите доктора.",
        model="Obrigada, doutora!",
        models=["Muito obrigada!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- МАГАЗИН ОДЕЖДЫ (вещь + цвет) ----------
 dict(id="roupa", unit=5, title="В магазине одежды", icon="👕",
  brief="Вам нравится {item.ru}, но нужен другой размер и цвет {cor.ru}.",
  slots=dict(
    item=[
      dict(pt="uma camisola", ru="свитер", key="camisola"),
      dict(pt="um vestido", ru="платье", key="vestido"),
      dict(pt="umas calças", ru="брюки", key="calças"),
      dict(pt="uma camisa", ru="рубашка", key="camisa"),
      dict(pt="um casaco", ru="куртка", key="casaco"),
      dict(pt="uma saia", ru="юбка", key="saia"),
      dict(pt="uns ténis", ru="кроссовки", key="ténis"),
    ],
    cor=[
      dict(pt="azul", ru="синий", key="azul"),
      dict(pt="preto", ru="чёрный", key="preto"),
      dict(pt="branco", ru="белый", key="branco"),
      dict(pt="vermelho", ru="красный", key="vermelho"),
      dict(pt="verde", ru="зелёный", key="verde"),
    ]),
  steps=[
   dict(say="Boa tarde! Posso ajudar?", ru="Добрый день! Могу помочь?",
        task="Скажите, что ищете: {item.ru}.",
        model="Boa tarde! Procuro {item.pt}.",
        models=["Queria {item.pt}.", "Procuro {item.pt}, por favor."],
        keys=[["{item.key}"]]),
   dict(say="Temos estes modelos. Gosta?", ru="У нас вот такие модели. Нравится?",
        task="Да, но спросите, есть ли другой размер.",
        model="Sim, mas tem outro tamanho?",
        models=["Gosto, mas tem outro tamanho?", "Sim. Tem tamanho maior?"],
        keys=[["tamanho"]]),
   dict(say="Temos em M e em L. E temos também noutras cores.", ru="Есть M и L. И есть другие цвета.",
        task="Спросите, есть ли цвет {cor.ru}.",
        model="Tem em {cor.pt}?",
        models=["Há em {cor.pt}?", "Tem esta cor em {cor.pt}?"],
        keys=[["{cor.key}"]]),
   dict(say="Sim! Aqui está. Quer experimentar?", ru="Да! Вот. Хотите примерить?",
        task="Да, хотите. Спросите потом, сколько стоит.",
        model="Sim, quero. Quanto custa?",
        models=["Quero, sim. Quanto é?"],
        keys=[["quero","sim"],["quanto"]]),
  ]),

 # ---------- КАССА (город, день, туда/обратно, платформа) ----------
 dict(id="bilheteira", unit=4, title="В билетной кассе", icon="🎫",
  brief="Купите {n.ru} до {dest.pt} на {dia.ru} ({tipo.ru}) и узнайте, с какой платформы поезд.",
  slots=dict(
    dest=[
      dict(pt="o Porto", key="porto"),
      dict(pt="Coimbra", key="coimbra"),
      dict(pt="Faro", key="faro"),
      dict(pt="Braga", key="braga"),
      dict(pt="Lisboa", key="lisboa"),
    ],
    dia=[
      dict(pt="sábado de manhã", ru="субботу утром", key="sábado"),
      dict(pt="domingo à tarde", ru="воскресенье днём", key="domingo"),
      dict(pt="sexta-feira à noite", ru="вечер пятницы", key="sexta"),
      dict(pt="amanhã de manhã", ru="завтра утром", key="amanhã"),
    ],
    tipo=[
      dict(pt="ida e volta", ru="туда и обратно", key="ida e volta"),
      dict(pt="só ida", ru="только туда", key="só ida"),
    ],
    n=[
      dict(pt="um bilhete", ru="один билет", key="um bilhete"),
      dict(pt="dois bilhetes", ru="два билета", key="dois bilhetes"),
    ]),
  steps=[
   dict(say="Bom dia! Faz favor.", ru="Доброе утро! Слушаю.",
        task="Попросите {n.ru} до {dest.pt}.",
        model="Bom dia! {n.pt} para {dest.pt}, por favor.",
        models=["Queria {n.pt} para {dest.pt}."],
        keys=[["bilhete"],["{dest.key}"]]),
   dict(say="Para quando?", ru="На когда?",
        task="На {dia.ru}.",
        model="Para {dia.pt}.",
        models=["{dia.pt}, por favor."],
        keys=[["{dia.key}"]]),
   dict(say="Ida e volta?", ru="Туда и обратно?",
        task="Ответьте: {tipo.ru}. И спросите цену.",
        model="{tipo.pt}, por favor. Quanto custa?",
        models=["{tipo.pt}. Quanto é?"],
        keys=[["{tipo.key}"],["quanto"]]),
   dict(say="São vinte e seis euros.", ru="Двадцать шесть евро.",
        task="Спросите, с какой платформы (linha) отходит поезд.",
        model="De que linha parte o comboio?",
        models=["O comboio parte de que linha?", "Qual é a linha?"],
        keys=[["linha"]]),
   dict(say="Parte da linha três. Boa viagem!", ru="С третьей платформы. Счастливого пути!",
        task="Поблагодарите.",
        model="Obrigada! Bom dia!",
        models=["Muito obrigada!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- ОТЕЛЬ (люди/срок + удобства) ----------
 dict(id="hotel", unit=8, title="В отеле", icon="🏨",
  brief="Забронируйте номер на {pes.ru} на {per.ru}; спросите про завтрак и {extra.ru}.",
  slots=dict(
    pes=[
      dict(pt="duas pessoas", ru="двоих", key="duas"),
      dict(pt="uma pessoa", ru="одного", key="uma pessoa"),
    ],
    per=[
      dict(pt="este fim de semana", ru="эти выходные", key="fim de semana"),
      dict(pt="três noites", ru="три ночи", key="três noites"),
      dict(pt="uma semana", ru="неделю", key="uma semana"),
    ],
    extra=[
      dict(pt="piscina", ru="бассейн", key="piscina"),
      dict(pt="restaurante", ru="ресторан", key="restaurante"),
    ]),
  steps=[
   dict(say="Boa tarde! Hotel Central, em que posso ajudar?", ru="Добрый день! Отель «Сентрал», чем могу помочь?",
        task="Скажите, что хотите забронировать номер.",
        model="Boa tarde! Queria reservar um quarto.",
        models=["Quero reservar um quarto, por favor."],
        keys=[["reservar"],["quarto"]]),
   dict(say="Com certeza. Para quantas pessoas e para quando?", ru="Конечно. На сколько человек и на когда?",
        task="На {pes.ru}, на {per.ru}.",
        model="Para {pes.pt}, para {per.pt}.",
        models=["{pes.pt}, {per.pt}."],
        keys=[["{pes.key}"],["{per.key}"]]),
   dict(say="Temos um quarto disponível por setenta euros por noite.", ru="Есть номер за семьдесят евро за ночь.",
        task="Спросите, включён ли завтрак.",
        model="O pequeno-almoço está incluído?",
        models=["O preço inclui o pequeno-almoço?"],
        keys=[["pequeno-almoço","pequeno almoço"]]),
   dict(say="Sim, está incluído.", ru="Да, включён.",
        task="Спросите, есть ли в отеле {extra.ru}.",
        model="O hotel tem {extra.pt}?",
        models=["Têm {extra.pt}?", "Há {extra.pt} no hotel?"],
        keys=[["{extra.key}"]]),
   dict(say="Temos, sim! Fica reservado. Até já!", ru="Есть! Забронировано. До встречи!",
        task="Поблагодарите и попрощайтесь.",
        model="Muito obrigada! Boa tarde!",
        models=["Obrigada! Até já!"],
        keys=[["obrigad"]]),
  ]),

 # ---------- АРЕНДА МАШИНЫ (срок-слот) ----------
 dict(id="aluguer", unit=8, title="Аренда машины", icon="🚗",
  brief="В отпуске вы хотите арендовать машину на {per.ru}. Узнайте цену.",
  slots=dict(
    per=[
      dict(pt="dois dias: sábado e domingo", ru="два дня (выходные)", key="dois dias"),
      dict(pt="três dias", ru="три дня", key="três dias"),
      dict(pt="uma semana", ru="неделю", key="uma semana"),
    ]),
  steps=[
   dict(say="Bom dia! Em que posso ajudar?", ru="Доброе утро! Чем могу помочь?",
        task="Скажите, что хотите арендовать машину.",
        model="Bom dia! Queria alugar um carro.",
        models=["Quero alugar um carro, por favor."],
        keys=[["alugar"],["carro"]]),
   dict(say="Com certeza. Para quantos dias?", ru="Конечно. На сколько дней?",
        task="На {per.ru}.",
        model="Para {per.pt}.",
        models=["{per.pt}, por favor."],
        keys=[["{per.key}"]]),
   dict(say="Temos este por quarenta euros por dia.", ru="Есть вот эта, сорок евро в день.",
        task="Спросите, сколько это всего.",
        model="Quanto é no total?",
        models=["No total, quanto custa?"],
        keys=[["total","quanto"]]),
   dict(say="Só preciso do seu passaporte.", ru="Нужен только ваш паспорт.",
        task="Скажите «вот, пожалуйста» и поблагодарите.",
        model="Aqui está. Obrigada!",
        models=["Aqui está o passaporte. Obrigada!"],
        keys=[["aqui","obrigad"]]),
  ]),

 {'id': 'cabeleireiro',
  'unit': 4,
  'title': 'В парикмахерской',
  'icon': '💇',
  'brief': 'Запишитесь подстричься на завтра на 15:00.',
  'steps': [{'say': 'Boa tarde! Em que posso ajudar?',
             'ru': 'Добрый день! Чем могу помочь?',
             'task': 'Скажите, что хотите подстричь волосы.',
             'model': 'Boa tarde! Queria cortar o cabelo.',
             'models': ['Queria cortar o cabelo, por favor.',
                        'Boa tarde! Posso marcar um corte de cabelo?'],
             'keys': [['cortar'], ['cabelo']]},
            {'say': 'Com certeza. Para quando?',
             'ru': 'Конечно. На когда?',
             'task': 'На завтра, если можно.',
             'model': 'Para amanhã, se possível.',
             'models': ['Amanhã, se possível.', 'Para amanhã, por favor.'],
             'keys': [['amanhã']]},
            {'say': 'Amanhã temos às 10:00 ou às 15:00.',
             'ru': 'Завтра есть на 10:00 или на 15:00.',
             'task': 'Выберите три часа дня.',
             'model': 'Às três da tarde, por favor.',
             'models': ['Às 15:00, por favor.', 'Prefiro às três da tarde.'],
             'keys': [['três', '15']]},
            {'say': 'Perfeito, fica marcado. Até amanhã!',
             'ru': 'Отлично, записано. До завтра!',
             'task': 'Поблагодарите и попрощайтесь.',
             'model': 'Obrigada! Até amanhã!',
             'models': ['Muito obrigada! Até amanhã!', 'Obrigada, até amanhã.'],
             'keys': [['obrigad']]}]},
 {'id': 'direcoes',
  'unit': 4,
  'title': 'Спросить дорогу',
  'icon': '🗺',
  'brief': 'Вы ищете станцию метро. Спросите прохожего, как пройти и далеко ли это.',
  'steps': [{'say': 'Olá! Precisa de ajuda?',
             'ru': 'Здравствуйте! Вам нужна помощь?',
             'task': 'Спросите, где ближайшая станция метро.',
             'model': 'Onde fica a estação de metro mais próxima?',
             'models': ['Sabe onde fica a estação de metro?',
                        'Desculpe, onde é o metro mais próximo?'],
             'keys': [['onde fica', 'onde é', 'onde e'], ['metro']]},
            {'say': 'Vira na próxima rua à esquerda e depois na primeira à direita.',
             'ru': 'Поверните на следующей улице налево, потом на первой направо.',
             'task': 'Спросите, это близко.',
             'model': 'É perto?',
             'models': ['Fica perto?', 'É longe?'],
             'keys': [['perto', 'longe']]},
            {'say': 'Sim, são cinco minutos a pé.',
             'ru': 'Да, пять минут пешком.',
             'task': 'Поблагодарите.',
             'model': 'Muito obrigada!',
             'models': ['Obrigada pela ajuda!', 'Obrigada!'],
             'keys': [['obrigad']]}]},
 {'id': 'conhecer',
  'unit': 1,
  'title': 'Знакомство',
  'icon': '👋',
  'brief': 'Вы знакомитесь с новым коллегой. Представьтесь, скажите, откуда вы и чем занимаетесь.',
  'steps': [{'say': 'Olá! Eu sou o Miguel. Como te chamas?',
             'ru': 'Привет! Я Мигел. Как тебя зовут?',
             'task': 'Поздоровайтесь и назовите своё имя.',
             'model': 'Olá! Eu chamo-me Ana.',
             'models': ['Olá! Eu sou a Ana.', 'Olá, Miguel! Chamo-me Ana.'],
             'keys': [['olá', 'bom dia', 'boa tarde'], ['chamo-me', 'chamo me', 'sou']]},
            {'say': 'Muito prazer, Ana! De onde és?',
             'ru': 'Очень приятно, Ана! Откуда ты?',
             'task': 'Скажите, что вы из России, но живёте в Лиссабоне.',
             'model': 'Sou da Rússia, mas moro em Lisboa.',
             'models': ['Eu sou da Rússia e moro em Lisboa.'],
             'keys': [['rússia', 'russia'], ['lisboa']]},
            {'say': 'Que bom! E o que fazes?',
             'ru': 'Здорово! А чем занимаешься?',
             'task': 'Скажите свою профессию (например, что вы учительница).',
             'model': 'Sou professora.',
             'models': ['Eu sou professora.', 'Trabalho numa escola. Sou professora.'],
             'keys': [['sou', 'trabalho']]},
            {'say': 'Boa! Bem-vinda a Portugal!',
             'ru': 'Отлично! Добро пожаловать в Португалию!',
             'task': 'Поблагодарите и скажите «очень приятно».',
             'model': 'Obrigada! Muito prazer!',
             'models': ['Muito obrigada! Prazer!'],
             'keys': [['obrigad']]}]},
 {'id': 'familia',
  'unit': 2,
  'title': 'Расскажите о семье',
  'icon': '👨\u200d👩\u200d👧',
  'brief': 'Новая знакомая расспрашивает о вашей семье. Расскажите про родителей и брата.',
  'steps': [{'say': 'Tens uma família grande?',
             'ru': 'У тебя большая семья?',
             'task': 'Скажите: нет, у вас есть родители и один брат.',
             'model': 'Não, tenho os meus pais e um irmão.',
             'models': ['Não. Tenho pais e um irmão.',
                        'Não, não é grande. Tenho os pais e um irmão.'],
             'keys': [['pais'], ['irmão', 'irmao']]},
            {'say': 'E o que faz o teu irmão?',
             'ru': 'А чем занимается твой брат?',
             'task': 'Скажите, что он инженер и работает в Москве.',
             'model': 'Ele é engenheiro e trabalha em Moscovo.',
             'models': ['O meu irmão é engenheiro. Trabalha em Moscovo.'],
             'keys': [['engenheiro'], ['trabalha']]},
            {'say': 'Os teus pais também moram lá?',
             'ru': 'Родители тоже там живут?',
             'task': 'Да — скажите, что они живут там же.',
             'model': 'Sim, eles também moram lá.',
             'models': ['Sim, os meus pais moram lá.', 'Sim, também.'],
             'keys': [['sim']]},
            {'say': 'Que bom! A família é muito importante.',
             'ru': 'Как хорошо! Семья — это очень важно.',
             'task': 'Согласитесь и скажите, что очень любите свою семью.',
             'model': 'Sim! Eu adoro a minha família.',
             'models': ['É verdade. Adoro a minha família.'],
             'keys': [['adoro', 'gosto'], ['família', 'familia']]}]},
 {'id': 'planos',
  'unit': 5,
  'title': 'Планы и погода',
  'icon': '⛅',
  'brief': 'Подруга зовёт вас на пляж в субботу. Обсудите погоду и договоритесь.',
  'steps': [{'say': 'Vamos à praia no sábado?',
             'ru': 'Пойдём на пляж в субботу?',
             'task': 'Спросите, какая будет погода.',
             'model': 'Como vai estar o tempo?',
             'models': ['Vai estar bom tempo?', 'Vai estar sol?'],
             'keys': [['tempo', 'sol']]},
            {'say': 'Vai estar sol e muito calor!',
             'ru': 'Будет солнце и очень жарко!',
             'task': 'Отлично — согласитесь и скажите, что возьмёте купальник и шляпу.',
             'model': 'Boa! Vou levar o biquíni e um chapéu.',
             'models': ['Ótimo! Levo o biquíni e o chapéu.', 'Sim! Vou levar o biquíni.'],
             'keys': [['biquíni', 'biquini', 'levar', 'levo']]},
            {'say': 'Eu levo água e fruta. A que horas vamos?',
             'ru': 'Я возьму воду и фрукты. Во сколько едем?',
             'task': 'Предложите в десять утра.',
             'model': 'Às dez da manhã?',
             'models': ['Vamos às dez da manhã.', 'Às 10:00, pode ser?'],
             'keys': [['dez', '10']]},
            {'say': 'Perfeito! Até sábado!',
             'ru': 'Отлично! До субботы!',
             'task': 'Попрощайтесь до субботы.',
             'model': 'Até sábado!',
             'models': ['Combinado! Até sábado!'],
             'keys': [['sábado', 'sabado']]}]},
 {'id': 'farmacia2',
  'unit': 6,
  'title': 'В аптеке · для ребёнка',
  'icon': '🧒',
  'brief': 'У ребёнка температура и болит горло. Спросите лекарство и как его принимать.',
  'steps': [{'say': 'Boa tarde! O que deseja?',
             'ru': 'Добрый день! Что желаете?',
             'task': 'Скажите, что у вашего сына температура и болит горло.',
             'model': 'O meu filho tem febre e dói-lhe a garganta.',
             'models': ['Boa tarde! O meu filho tem febre e dores de garganta.'],
             'keys': [['febre'], ['garganta']]},
            {'say': 'Quantos anos tem o menino?',
             'ru': 'Сколько лет мальчику?',
             'task': 'Скажите: семь лет.',
             'model': 'Tem sete anos.',
             'models': ['Ele tem sete anos.', 'Sete anos.'],
             'keys': [['sete', '7']]},
            {'say': 'Este medicamento é muito bom para crianças.',
             'ru': 'Это лекарство очень хорошее для детей.',
             'task': 'Спросите, сколько раз в день принимать.',
             'model': 'Quantas vezes por dia?',
             'models': ['Ele toma quantas vezes por dia?', 'Quantas vezes por dia é que ele toma?'],
             'keys': [['quantas vezes', 'por dia']]},
            {'say': 'Duas vezes por dia, depois das refeições.',
             'ru': 'Два раза в день, после еды.',
             'task': 'Поблагодарите и попрощайтесь.',
             'model': 'Muito obrigada! Boa tarde!',
             'models': ['Obrigada! Adeus!'],
             'keys': [['obrigad']]}]},
 {'id': 'convite',
  'unit': 7,
  'title': 'Приглашение на праздник',
  'icon': '🎂',
  'brief': 'Пригласите друга на свой день рождения в субботу и ответьте на его вопросы.',
  'steps': [{'say': 'Olá! Tudo bem?',
             'ru': 'Привет! Как дела?',
             'task': 'Поздоровайтесь и пригласите его на ваш день рождения в субботу.',
             'model': 'Olá! No sábado é o meu aniversário. Queres vir à festa?',
             'models': ['Tudo bem! Sábado faço anos. Vens à minha festa?'],
             'keys': [['aniversário', 'aniversario', 'anos'], ['festa', 'vir', 'vens']]},
            {'say': 'Que bom! Parabéns! A que horas começa?',
             'ru': 'Здорово! Поздравляю! Во сколько начало?',
             'task': 'Скажите: в восемь вечера, у вас дома.',
             'model': 'Às oito da noite, na minha casa.',
             'models': ['Começa às oito da noite, em minha casa.'],
             'keys': [['oito', '8'], ['casa']]},
            {'say': 'Levo alguma coisa? Um bolo, uma bebida?',
             'ru': 'Мне что-нибудь принести? Торт, напитки?',
             'task': 'Скажите, что ничего не нужно — только он сам.',
             'model': 'Não é preciso, obrigada. Só tens de vir!',
             'models': ['Não, obrigada. Não precisas de trazer nada.'],
             'keys': [['não', 'nao']]},
            {'say': 'Combinado! Até sábado, então!',
             'ru': 'Договорились! Тогда до субботы!',
             'task': 'Попрощайтесь до субботы.',
             'model': 'Até sábado!',
             'models': ['Combinado! Até sábado!'],
             'keys': [['sábado', 'sabado']]}]},
]
