# -*- coding: utf-8 -*-
"""Тематические диалоги с голосовым ответом.
Собеседник говорит реплику (TTS), ученик отвечает в микрофон (Web Speech API, pt-PT).
Проверка — по ключевым словам: реплика засчитывается, если распознались нужные слова.

Формат шага: dict(
  say   = реплика собеседника (pt),
  ru    = перевод реплики,
  task  = что нужно сказать (по-русски),
  model = образцовый ответ (pt) — показывается после попытки,
  keys  = [[синонимы]...] — каждая группа должна встретиться в ответе)
"""

DIALOGS = [
 dict(id="cafe", unit=3, title="В кафе", icon="☕",
  brief="Вы в кафе. Поздоровайтесь, закажите кофе и пирожное, попросите счёт.",
  steps=[
   dict(say="Bom dia! Faz favor.", ru="Доброе утро! Слушаю вас.",
        task="Поздоровайтесь и закажите один кофе, пожалуйста.",
        model="Bom dia! Um café, por favor.",
        models=['Olá! Queria um café, por favor.', 'Bom dia! Quero um café, faz favor.'],
        keys=[["bom dia","boa tarde","olá"],["café"],["por favor","faz favor","queria","quero"]]),
   dict(say="Com certeza. Mais alguma coisa?", ru="Конечно. Что-нибудь ещё?",
        task="Да — попросите ещё паштел де ната.",
        model="Sim, um pastel de nata, por favor.",
        models=['Queria também um pastel de nata.', 'Sim, e um pastel de nata.'],
        keys=[["pastel","nata"]]),
   dict(say="Aqui está. Bom apetite!", ru="Вот, пожалуйста. Приятного аппетита!",
        task="Поблагодарите и попросите счёт.",
        model="Obrigada! A conta, por favor.",
        models=['Muito obrigada! Pode trazer a conta?', 'Obrigada. Quanto é?'],
        keys=[["obrigad"],["conta"]]),
   dict(say="São dois euros e cinquenta. Até logo!", ru="Два евро пятьдесят. До скорого!",
        task="Попрощайтесь.",
        model="Até logo!",
        models=['Adeus!', 'Obrigada, até logo!', 'Até amanhã!'],
        keys=[["até logo","adeus","até amanhã","bom dia","obrigada"]]),
  ]),
 dict(id="restaurante", unit=3, title="В ресторане", icon="🍽",
  brief="Вы ужинаете в ресторане. Спросите блюдо дня, закажите рыбу и стакан вина, потом счёт.",
  steps=[
   dict(say="Boa noite! Uma mesa para quantas pessoas?", ru="Добрый вечер! Столик на сколько человек?",
        task="Скажите: на одного, пожалуйста.",
        model="Para uma pessoa, por favor.",
        models=['Para mim, por favor.', 'Uma mesa para uma pessoa.'],
        keys=[["uma pessoa","para um","para mim"]]),
   dict(say="Aqui está a ementa. Hoje temos peixe muito fresco.", ru="Вот меню. Сегодня очень свежая рыба.",
        task="Спросите, какое сегодня блюдо дня.",
        model="Qual é o prato do dia?",
        models=['O que é o prato do dia?', 'Têm prato do dia?'],
        keys=[["prato do dia","prato de dia"]]),
   dict(say="É bacalhau com batatas. É muito bom!", ru="Треска с картофелем. Очень вкусно!",
        task="Закажите его и стакан белого вина.",
        model="Queria o bacalhau e um copo de vinho branco, por favor.",
        models=['O bacalhau e um vinho branco, por favor.', 'Para mim, o bacalhau e um copo de vinho.'],
        keys=[["bacalhau"],["vinho"]]),
   dict(say="Foi tudo do seu agrado?", ru="Вам всё понравилось?",
        task="Скажите, что всё было очень вкусно, и попросите счёт.",
        model="Sim, foi tudo muito bom. A conta, por favor.",
        models=['Sim, gostei muito. Pode trazer a conta?', 'Foi tudo muito bom. A conta, faz favor.'],
        keys=[["muito bom","muito boa","foi bom","gostei"],["conta"]]),
  ]),
 dict(id="farmacia", unit=6, title="В аптеке", icon="💊",
  brief="У вас болит голова и есть кашель. Купите обезболивающее и спросите про сироп.",
  steps=[
   dict(say="Boa tarde! Em que posso ajudar?", ru="Добрый день! Чем могу помочь?",
        task="Скажите, что у вас болит голова, и попросите обезболивающее.",
        model="Boa tarde! Dói-me a cabeça. Queria um analgésico, por favor.",
        models=['Dói-me a cabeça. Tem um analgésico?', 'Boa tarde! Preciso de um analgésico, dói-me a cabeça.'],
        keys=[["cabeça"],["analgésico","comprimido"]]),
   dict(say="Claro. Este é muito bom. Mais alguma coisa?", ru="Конечно. Вот это очень хорошее. Что-то ещё?",
        task="Да — скажите, что у вас кашель, и спросите, что они рекомендуют.",
        model="Sim, tenho tosse. O que recomenda?",
        models=['Também tenho tosse. O que me recomenda?', 'Sim, e tenho tosse.'],
        keys=[["tosse"]]),
   dict(say="Tome este medicamento duas vezes por dia.", ru="Принимайте это лекарство два раза в день.",
        task="Спросите, сколько это стоит.",
        model="Quanto custa?",
        models=['Quanto é?', 'Quanto custa, por favor?'],
        keys=[["quanto custa","quanto é","quanto e"]]),
   dict(say="São oito euros e vinte.", ru="Восемь евро двадцать.",
        task="Поблагодарите и попрощайтесь.",
        model="Obrigada! Boa tarde!",
        models=['Muito obrigada! Adeus!', 'Obrigada, até logo!'],
        keys=[["obrigad"]]),
  ]),
 dict(id="medico", unit=6, title="У врача", icon="🩺",
  brief="Вы на приёме. Расскажите: вы устали, плохо спите, болит спина.",
  steps=[
   dict(say="Bom dia! Como se sente?", ru="Доброе утро! Как вы себя чувствуете?",
        task="Скажите, что чувствуете себя плохо и всегда усталая.",
        model="Sinto-me mal. Estou sempre cansada.",
        models=['Não me sinto bem. Estou muito cansada.', 'Sinto-me mal e sempre cansada.'],
        keys=[["sinto","mal","cansad"]]),
   dict(say="E dorme bem?", ru="А спите хорошо?",
        task="Скажите, что нет — спите плохо и у вас бессонница.",
        model="Não, durmo mal. Tenho insónias.",
        models=['Durmo muito mal, tenho insónias.', 'Não, não durmo bem. Tenho insónias.'],
        keys=[["durmo mal","não durmo","dormir mal","insóni"]]),
   dict(say="Tem dores?", ru="Боли есть?",
        task="Да — скажите, что болит спина.",
        model="Sim, doem-me as costas.",
        models=['Doem-me as costas.', 'Sim, tenho dores nas costas.'],
        keys=[["costas"]]),
   dict(say="Vamos fazer análises. Durma mais e beba muita água.", ru="Сделаем анализы. Спите больше и пейте много воды.",
        task="Поблагодарите доктора.",
        model="Obrigada, doutora!",
        models=['Muito obrigada, doutora!', 'Obrigada!'],
        keys=[["obrigad"]]),
  ]),
 dict(id="mercado", unit=3, title="На рынке", icon="🥕",
  brief="Купите килограмм помидоров и полкило сыра, спросите цену.",
  steps=[
   dict(say="Bom dia! O que deseja?", ru="Доброе утро! Что желаете?",
        task="Попросите килограмм помидоров.",
        model="Bom dia! Um quilo de tomate, por favor.",
        models=['Queria um quilo de tomate, por favor.', 'Bom dia! Um quilo de tomate, faz favor.'],
        keys=[["quilo"],["tomate"]]),
   dict(say="Com certeza. Mais alguma coisa?", ru="Конечно. Ещё что-нибудь?",
        task="Да — спросите, есть ли у них сыр.",
        model="Sim, tem queijo?",
        models=['Tem queijo?', 'Sim, queria queijo. Tem?'],
        keys=[["queijo"]]),
   dict(say="Temos, sim. É deste, da Serra.", ru="Есть. Вот этот, с горы Серра.",
        task="Спросите, сколько стоит.",
        model="Quanto custa?",
        models=['Quanto é?', 'Quanto custa, por favor?'],
        keys=[["quanto custa","quanto é","quanto e"]]),
   dict(say="São seis euros o quilo.", ru="Шесть евро за килограмм.",
        task="Скажите: полкило, пожалуйста.",
        model="Meio quilo, por favor.",
        models=['Queria meio quilo.', 'Meio quilo, faz favor.'],
        keys=[["meio quilo","meio-quilo"]]),
  ]),
 dict(id="roupa", unit=5, title="В магазине одежды", icon="👕",
  brief="Вам нравится свитер, но нужен другой размер и другой цвет.",
  steps=[
   dict(say="Boa tarde! Posso ajudar?", ru="Добрый день! Могу помочь?",
        task="Скажите, что ищете свитер.",
        model="Boa tarde! Procuro uma camisola.",
        models=['Procuro uma camisola.', 'Boa tarde! Queria uma camisola.'],
        keys=[["camisola"]]),
   dict(say="Temos estas. Gosta?", ru="У нас есть вот эти. Нравится?",
        task="Да, но спросите, есть ли другой размер.",
        model="Sim, mas tem outro tamanho?",
        models=['Gosto, mas tem outro tamanho?', 'Sim. Tem tamanho maior?'],
        keys=[["outro tamanho","tamanho"]]),
   dict(say="Temos em M e em L. E temos também noutras cores.", ru="Есть M и L. И есть другие цвета.",
        task="Спросите, есть ли синяя.",
        model="Tem em azul?",
        models=['Tem esta camisola em azul?', 'Há em azul?'],
        keys=[["azul"]]),
   dict(say="Sim! Aqui está. Quer experimentar?", ru="Да! Вот. Хотите примерить?",
        task="Да, хотите. Спросите потом, сколько стоит.",
        model="Sim, quero. Quanto custa?",
        models=['Sim, quero experimentar. Quanto custa?', 'Quero, sim. Quanto é?'],
        keys=[["quero","sim"],["quanto"]]),
  ]),
 dict(id="cabeleireiro", unit=4, title="В парикмахерской", icon="💇",
  brief="Запишитесь подстричься на завтра на 15:00.",
  steps=[
   dict(say="Boa tarde! Em que posso ajudar?", ru="Добрый день! Чем могу помочь?",
        task="Скажите, что хотите подстричь волосы.",
        model="Boa tarde! Queria cortar o cabelo.",
        models=['Queria cortar o cabelo, por favor.', 'Boa tarde! Posso marcar um corte de cabelo?'],
        keys=[["cortar"],["cabelo"]]),
   dict(say="Com certeza. Para quando?", ru="Конечно. На когда?",
        task="На завтра, если можно.",
        model="Para amanhã, se possível.",
        models=['Amanhã, se possível.', 'Para amanhã, por favor.'],
        keys=[["amanhã"]]),
   dict(say="Amanhã temos às 10:00 ou às 15:00.", ru="Завтра есть на 10:00 или на 15:00.",
        task="Выберите три часа дня.",
        model="Às três da tarde, por favor.",
        models=['Às 15:00, por favor.', 'Prefiro às três da tarde.'],
        keys=[["três","15"]]),
   dict(say="Perfeito, fica marcado. Até amanhã!", ru="Отлично, записано. До завтра!",
        task="Поблагодарите и попрощайтесь.",
        model="Obrigada! Até amanhã!",
        models=['Muito obrigada! Até amanhã!', 'Obrigada, até amanhã.'],
        keys=[["obrigad"]]),
  ]),
 dict(id="bilheteira", unit=4, title="В билетной кассе", icon="🎫",
  brief="Купите два билета на поезд в Порту на субботу утром.",
  steps=[
   dict(say="Bom dia! Faz favor.", ru="Доброе утро! Слушаю.",
        task="Попросите два билета в Порту.",
        model="Bom dia! Dois bilhetes para o Porto, por favor.",
        models=['Queria dois bilhetes para o Porto.', 'Dois bilhetes para o Porto, faz favor.'],
        keys=[["dois bilhetes","bilhete"],["porto"]]),
   dict(say="Para quando?", ru="На когда?",
        task="На субботу утром.",
        model="Para sábado de manhã.",
        models=['No sábado de manhã.', 'Sábado de manhã, por favor.'],
        keys=[["sábado","sabado"]]),
   dict(say="Temos um comboio às 9:30. Ida e volta?", ru="Есть поезд в 9:30. Туда и обратно?",
        task="Да, туда и обратно. Спросите, сколько стоит.",
        model="Sim, ida e volta. Quanto custa?",
        models=['Ida e volta, por favor. Quanto é?', 'Sim, ida e volta. Quanto é?'],
        keys=[["ida e volta","sim"],["quanto"]]),
   dict(say="São quarenta e dois euros.", ru="Сорок два евро.",
        task="Скажите «хорошо» и поблагодарите.",
        model="Está bem. Obrigada!",
        models=['Muito bem, obrigada!', 'Está bem, obrigada.'],
        keys=[["obrigad","está bem","esta bem"]]),
  ]),
 dict(id="hotel", unit=8, title="В отеле", icon="🏨",
  brief="Забронируйте номер на два человека на выходные, спросите про завтрак.",
  steps=[
   dict(say="Boa tarde! Hotel Central, em que posso ajudar?", ru="Добрый день! Отель «Сентрал», чем могу помочь?",
        task="Скажите, что хотите забронировать номер.",
        model="Boa tarde! Queria reservar um quarto.",
        models=['Queria reservar um quarto, por favor.', 'Boa tarde! É possível reservar um quarto?'],
        keys=[["reservar"],["quarto"]]),
   dict(say="Com certeza. Para quantas pessoas e para quando?", ru="Конечно. На сколько человек и на когда?",
        task="На двоих, на эти выходные.",
        model="Para duas pessoas, para este fim de semana.",
        models=['Para duas pessoas, este fim de semana.', 'Duas pessoas, para o fim de semana.'],
        keys=[["duas pessoas","dois"],["fim de semana"]]),
   dict(say="Temos um quarto disponível por oitenta euros por noite.", ru="Есть номер за восемьдесят евро за ночь.",
        task="Спросите, включён ли завтрак.",
        model="O pequeno-almoço está incluído?",
        models=['O preço inclui o pequeno-almoço?', 'Está incluído o pequeno-almoço?'],
        keys=[["pequeno-almoço","pequeno almoço"]]),
   dict(say="Sim, está incluído. Fica reservado!", ru="Да, включён. Забронировано!",
        task="Поблагодарите и попрощайтесь.",
        model="Muito obrigada! Boa tarde!",
        models=['Obrigada! Até logo!', 'Muito obrigada, boa tarde.'],
        keys=[["obrigad"]]),
  ]),
 dict(id="direcoes", unit=4, title="Спросить дорогу", icon="🗺",
  brief="Вы ищете станцию метро. Спросите прохожего, как пройти и далеко ли это.",
  steps=[
   dict(say="Olá! Precisa de ajuda?", ru="Здравствуйте! Вам нужна помощь?",
        task="Спросите, где ближайшая станция метро.",
        model="Onde fica a estação de metro mais próxima?",
        models=['Sabe onde fica a estação de metro?', 'Desculpe, onde é o metro mais próximo?'],
        keys=[["onde fica","onde é","onde e"],["metro"]]),
   dict(say="Vira na próxima rua à esquerda e depois na primeira à direita.", ru="Поверните на следующей улице налево, потом на первой направо.",
        task="Спросите, это близко.",
        model="É perto?",
        models=['Fica perto?', 'É longe?'],
        keys=[["perto","longe"]]),
   dict(say="Sim, são cinco minutos a pé.", ru="Да, пять минут пешком.",
        task="Поблагодарите.",
        model="Muito obrigada!",
        models=['Obrigada pela ajuda!', 'Obrigada!'],
        keys=[["obrigad"]]),
  ]),

 dict(id="conhecer", unit=1, title="Знакомство", icon="👋",
  brief="Вы знакомитесь с новым коллегой. Представьтесь, скажите, откуда вы и чем занимаетесь.",
  steps=[
   dict(say="Olá! Eu sou o Miguel. Como te chamas?", ru="Привет! Я Мигел. Как тебя зовут?",
        task="Поздоровайтесь и назовите своё имя.",
        model="Olá! Eu chamo-me Ana.",
        models=["Olá! Eu sou a Ana.", "Olá, Miguel! Chamo-me Ana."],
        keys=[["olá","bom dia","boa tarde"],["chamo-me","chamo me","sou"]]),
   dict(say="Muito prazer, Ana! De onde és?", ru="Очень приятно, Ана! Откуда ты?",
        task="Скажите, что вы из России, но живёте в Лиссабоне.",
        model="Sou da Rússia, mas moro em Lisboa.",
        models=["Eu sou da Rússia e moro em Lisboa."],
        keys=[["rússia","russia"],["lisboa"]]),
   dict(say="Que bom! E o que fazes?", ru="Здорово! А чем занимаешься?",
        task="Скажите свою профессию (например, что вы учительница).",
        model="Sou professora.",
        models=["Eu sou professora.", "Trabalho numa escola. Sou professora."],
        keys=[["sou","trabalho"]]),
   dict(say="Boa! Bem-vinda a Portugal!", ru="Отлично! Добро пожаловать в Португалию!",
        task="Поблагодарите и скажите «очень приятно».",
        model="Obrigada! Muito prazer!",
        models=["Muito obrigada! Prazer!"],
        keys=[["obrigad"]]),
  ]),
 dict(id="familia", unit=2, title="Расскажите о семье", icon="👨‍👩‍👧",
  brief="Новая знакомая расспрашивает о вашей семье. Расскажите про родителей и брата.",
  steps=[
   dict(say="Tens uma família grande?", ru="У тебя большая семья?",
        task="Скажите: нет, у вас есть родители и один брат.",
        model="Não, tenho os meus pais e um irmão.",
        models=["Não. Tenho pais e um irmão.", "Não, não é grande. Tenho os pais e um irmão."],
        keys=[["pais"],["irmão","irmao"]]),
   dict(say="E o que faz o teu irmão?", ru="А чем занимается твой брат?",
        task="Скажите, что он инженер и работает в Москве.",
        model="Ele é engenheiro e trabalha em Moscovo.",
        models=["O meu irmão é engenheiro. Trabalha em Moscovo."],
        keys=[["engenheiro"],["trabalha"]]),
   dict(say="Os teus pais também moram lá?", ru="Родители тоже там живут?",
        task="Да — скажите, что они живут там же.",
        model="Sim, eles também moram lá.",
        models=["Sim, os meus pais moram lá.", "Sim, também."],
        keys=[["sim"]]),
   dict(say="Que bom! A família é muito importante.", ru="Как хорошо! Семья — это очень важно.",
        task="Согласитесь и скажите, что очень любите свою семью.",
        model="Sim! Eu adoro a minha família.",
        models=["É verdade. Adoro a minha família."],
        keys=[["adoro","gosto"],["família","familia"]]),
  ]),
 dict(id="planos", unit=5, title="Планы и погода", icon="⛅",
  brief="Подруга зовёт вас на пляж в субботу. Обсудите погоду и договоритесь.",
  steps=[
   dict(say="Vamos à praia no sábado?", ru="Пойдём на пляж в субботу?",
        task="Спросите, какая будет погода.",
        model="Como vai estar o tempo?",
        models=["Vai estar bom tempo?", "Vai estar sol?"],
        keys=[["tempo","sol"]]),
   dict(say="Vai estar sol e muito calor!", ru="Будет солнце и очень жарко!",
        task="Отлично — согласитесь и скажите, что возьмёте купальник и шляпу.",
        model="Boa! Vou levar o biquíni e um chapéu.",
        models=["Ótimo! Levo o biquíni e o chapéu.", "Sim! Vou levar o biquíni."],
        keys=[["biquíni","biquini","levar","levo"]]),
   dict(say="Eu levo água e fruta. A que horas vamos?", ru="Я возьму воду и фрукты. Во сколько едем?",
        task="Предложите в десять утра.",
        model="Às dez da manhã?",
        models=["Vamos às dez da manhã.", "Às 10:00, pode ser?"],
        keys=[["dez","10"]]),
   dict(say="Perfeito! Até sábado!", ru="Отлично! До субботы!",
        task="Попрощайтесь до субботы.",
        model="Até sábado!",
        models=["Combinado! Até sábado!"],
        keys=[["sábado","sabado"]]),
  ]),
 dict(id="farmacia2", unit=6, title="В аптеке · для ребёнка", icon="🧒",
  brief="У ребёнка температура и болит горло. Спросите лекарство и как его принимать.",
  steps=[
   dict(say="Boa tarde! O que deseja?", ru="Добрый день! Что желаете?",
        task="Скажите, что у вашего сына температура и болит горло.",
        model="O meu filho tem febre e dói-lhe a garganta.",
        models=["Boa tarde! O meu filho tem febre e dores de garganta."],
        keys=[["febre"],["garganta"]]),
   dict(say="Quantos anos tem o menino?", ru="Сколько лет мальчику?",
        task="Скажите: семь лет.",
        model="Tem sete anos.",
        models=["Ele tem sete anos.", "Sete anos."],
        keys=[["sete","7"]]),
   dict(say="Este medicamento é muito bom para crianças.", ru="Это лекарство очень хорошее для детей.",
        task="Спросите, сколько раз в день принимать.",
        model="Quantas vezes por dia?",
        models=["Ele toma quantas vezes por dia?", "Quantas vezes por dia é que ele toma?"],
        keys=[["quantas vezes","por dia"]]),
   dict(say="Duas vezes por dia, depois das refeições.", ru="Два раза в день, после еды.",
        task="Поблагодарите и попрощайтесь.",
        model="Muito obrigada! Boa tarde!",
        models=["Obrigada! Adeus!"],
        keys=[["obrigad"]]),
  ]),
 dict(id="convite", unit=7, title="Приглашение на праздник", icon="🎂",
  brief="Пригласите друга на свой день рождения в субботу и ответьте на его вопросы.",
  steps=[
   dict(say="Olá! Tudo bem?", ru="Привет! Как дела?",
        task="Поздоровайтесь и пригласите его на ваш день рождения в субботу.",
        model="Olá! No sábado é o meu aniversário. Queres vir à festa?",
        models=["Tudo bem! Sábado faço anos. Vens à minha festa?"],
        keys=[["aniversário","aniversario","anos"],["festa","vir","vens"]]),
   dict(say="Que bom! Parabéns! A que horas começa?", ru="Здорово! Поздравляю! Во сколько начало?",
        task="Скажите: в восемь вечера, у вас дома.",
        model="Às oito da noite, na minha casa.",
        models=["Começa às oito da noite, em minha casa."],
        keys=[["oito","8"],["casa"]]),
   dict(say="Levo alguma coisa? Um bolo, uma bebida?", ru="Мне что-нибудь принести? Торт, напитки?",
        task="Скажите, что ничего не нужно — только он сам.",
        model="Não é preciso, obrigada. Só tens de vir!",
        models=["Não, obrigada. Não precisas de trazer nada."],
        keys=[["não","nao"]]),
   dict(say="Combinado! Até sábado, então!", ru="Договорились! Тогда до субботы!",
        task="Попрощайтесь до субботы.",
        model="Até sábado!",
        models=["Combinado! Até sábado!"],
        keys=[["sábado","sabado"]]),
  ]),
 dict(id="aluguer", unit=8, title="Аренда машины", icon="🚗",
  brief="В отпуске вы хотите арендовать машину на два дня. Узнайте цену.",
  steps=[
   dict(say="Bom dia! Em que posso ajudar?", ru="Доброе утро! Чем могу помочь?",
        task="Скажите, что хотите арендовать машину.",
        model="Bom dia! Queria alugar um carro.",
        models=["Quero alugar um carro, por favor."],
        keys=[["alugar"],["carro"]]),
   dict(say="Com certeza. Para quantos dias?", ru="Конечно. На сколько дней?",
        task="На два дня — субботу и воскресенье.",
        model="Para dois dias: sábado e domingo.",
        models=["Dois dias, o fim de semana."],
        keys=[["dois dias","fim de semana"]]),
   dict(say="Temos este por quarenta euros por dia.", ru="Есть вот эта, сорок евро в день.",
        task="Спросите, сколько это всего.",
        model="Quanto é no total?",
        models=["No total, quanto custa?", "Quanto custa no total?"],
        keys=[["total","quanto"]]),
   dict(say="São oitenta euros. Só preciso do seu passaporte.", ru="Восемьдесят евро. Нужен только ваш паспорт.",
        task="Скажите «вот, пожалуйста» и поблагодарите.",
        model="Aqui está. Obrigada!",
        models=["Aqui está o passaporte. Obrigada!"],
        keys=[["aqui","obrigad"]]),
  ]),
]