# -*- coding: utf-8 -*-
"""Перевод с русского на португальский. Эталон — фразы из Português a Valer 1,
поэтому лексика и грамматика не выходят за пределы пройденного A1."""

# (rule, русская фраза, эталон, [альтернативы], юнит)
TRANS = [
# --- U1: знакомство, ser/ter, -ar ---
("reflexos", "Меня зовут Жуан.", "Eu chamo-me João.", [], 1),
("reflexos", "Её не зовут Диана.", "Ela não se chama Diana.", [], 1),
("reflexos", "Как тебя зовут?", "Como te chamas?", ["Como é que te chamas?"], 1),
("reflexos", "Как вас зовут? (вежливо, к сеньоре)", "Como é que a senhora se chama?", ["Como se chama a senhora?"], 1),
("ser_estar", "Я из Анголы.", "Eu sou de Angola.", [], 1),
("ser_estar", "Вы из Ирана?", "Você é do Irão?", [], 1),
("ser_estar", "Мы из Тимора-Лешти.", "Nós somos de Timor-Leste.", [], 1),
("ser_estar", "Виолет — англичанка.", "A Violet é inglesa.", [], 1),
("ser_estar", "Пабло из Венесуэлы.", "O Pablo é da Venezuela.", [], 1),
("de_em_paises", "Рита из Лиссабона, но живёт в Коимбре.", "A Rita é de Lisboa, mas mora em Coimbra.", [], 1),
("de_em_paises", "Мы живём в Порту.", "Nós moramos no Porto.", [], 1),
("de_em_paises", "Дина из Хорватии, а Грегори из США.",
 "A Dina é da Croácia e o Gregory é dos Estados Unidos.", [], 1),
("pres_regulares", "Сколько тебе лет?", "Quantos anos tens?", ["Quantos anos é que tens?"], 1),
("pres_regulares", "Ане 25 лет.", "A Ana tem 25 anos.", ["A Ana tem vinte e cinco anos."], 1),
("pres_regulares", "Я живу в Порту с Карлушем.", "Eu moro no Porto com o Carlos.", [], 1),
("pres_regulares", "Лукаш и я говорим на китайском.", "O Lucas e eu falamos mandarim.", [], 1),
("pres_regulares", "По выходным я работаю в баре.", "Ao fim de semana, eu trabalho num bar.", [], 1),
("pres_regulares", "Ты живёшь в центре города?", "Tu moras no centro da cidade?", [], 1),
("artigos", "Бразилиа — столица Бразилии.", "Brasília é a capital do Brasil.", [], 1),
("artigos", "Муж Ракел — норвежец.", "O marido da Raquel é norueguês.", [], 1),

# --- U2: семья, ser/estar, -er, possessivos ---
("ser_estar", "Моя сестра — вегетарианка.", "A minha irmã é vegetariana.", [], 2),
("ser_estar", "Она не ест мясо, но пьёт молоко.", "Ela não come carne, mas bebe leite.", [], 2),
("pres_regulares", "Деннис и Олаф живут в центре Лиссабона.", "O Dennis e o Olaf vivem no centro de Lisboa.", [], 2),
("pres_regulares", "Ты пишешь сообщения или звонишь друзьям?",
 "Tu escreves mensagens ou telefonas aos teus amigos?", [], 2),
("pres_regulares", "Я не знаю Жуана, но моя сестра знает.",
 "Eu não conheço o João, mas a minha irmã conhece.", [], 2),
("pres_regulares", "Дети засыпают до девяти.", "As crianças adormecem antes das nove.", [], 2),
("pres_regulares", "Мы едим биопродукты.", "Nós comemos produtos biológicos.", [], 2),
("pres_regulares", "Я ем хлопья с молоком.", "Eu como cereais com leite.", [], 2),
("possessivos", "Эмилия, это твоя бутылка воды?", "Emília, esta garrafa de água é tua?", [], 2),
("possessivos", "Мы с братьями бегаем на пляже.", "Eu e os meus irmãos corremos na praia.", [], 2),
("lugar", "Книга лежит рядом с пеналом.", "O livro está ao lado do estojo.", [], 2),
("lugar", "Кот под стулом.", "O gato está debaixo da cadeira.", [], 2),
("lugar", "Кот между столом и сумкой.", "O gato está entre a mesa e a mala.", [], 2),

# --- U3: еда, -ir, рефлексивы, время ---
("pres_regulares", "Я предпочитаю рыбу на ужин.", "Eu prefiro comer peixe ao jantar.", ["Eu prefiro peixe ao jantar."], 3),
("pres_regulares", "Мы решаем поесть на террасе, потому что жарко.",
 "Nós decidimos comer na esplanada, pois está calor.", ["Nós decidimos comer na esplanada, porque está calor."], 3),
("pres_regulares", "Они надевают куртку, потому что холодно.", "Eles vestem o casaco, porque está frio.", [], 3),
("pres_regulares", "Майте умеет готовить португальские блюда.", "A Maite consegue cozinhar pratos portugueses.", [], 3),
("pres_regulares", "Самолёт Бруны вылетает в Рио-де-Жанейро в семь вечера.",
 "O avião da Bruna parte para o Rio de Janeiro às sete da tarde.", [], 3),
("reflexos", "Утром я встаю в 7:00.", "De manhã, eu levanto-me às 7:00.", [], 3),
("reflexos", "В будни мы ложимся до полуночи.", "Durante a semana, nós deitamo-nos antes da meia-noite.", [], 3),
("reflexos", "Мы быстро одеваемся.", "Nós vestimo-nos rapidamente.", [], 3),
("reflexos", "Преподаватель не садится во время уроков.", "O professor não se senta durante as aulas.", [], 3),
("reflexos", "Во сколько Катя встаёт по субботам?",
 "A que horas é que a Cátia se levanta ao sábado?", [], 3),
("pres_regulares", "Я слушаю преподавателей внимательно.", "Eu ouço os professores com atenção.", [], 3),
("pres_regulares", "Мы часто видим закат на пляже.", "Nós vemos o pôr do sol na praia muitas vezes.", [], 3),
("pres_regulares", "Я выхожу из дома в 19:00.", "Eu saio de casa às 19:00.", [], 3),
("pres_regulares", "Мы с друзьями каждую неделю ходим в кино.",
 "Eu e os meus amigos vamos ao cinema todas as semanas.", [], 3),
("prep_tempo", "По пятницам вечером я обычно хожу в кино.",
 "À sexta-feira à noite, costumo ir ao cinema.", [], 3),
("prep_tempo", "Урок начинается в 15:30 и заканчивается в 17:00.",
 "A aula começa às 15:30 e termina às 17:00.", [], 3),
("prep_tempo", "В воскресенье поедем в Порту?", "No domingo, vamos ao Porto?", [], 3),
("prep_tempo", "Он приходит в пять вечера.", "Ele chega às cinco da tarde.", [], 3),

# --- U4: дом, город, ter de, estar a, irregulares II ---
("ter_de", "Очень холодно. Нам надо надеть куртку.", "Está muito frio. Temos de vestir o casaco.", [], 4),
("ter_de", "Тебе надо сходить к врачу.", "Tu tens de ir ao médico.", [], 4),
("ter_de", "Завтра у нас экзамен. Нам надо позаниматься.", "Amanhã, temos um exame. Temos de estudar.", [], 4),
("ter_de", "Им надо открыть окно.", "Eles têm de abrir a janela.", [], 4),
("ter_de", "На этой неделе мне надо подстричься.", "Esta semana, tenho de cortar o cabelo.", [], 4),
("ter_de", "Мне надо сесть на метро в 8:00.", "Eu tenho de apanhar o metro das 8:00.", [], 4),
("estar_a", "Мои родители сейчас готовят ужин.", "Os meus pais estão a fazer o jantar.", [], 4),
("estar_a", "Мы сейчас смотрим фильм.", "Nós estamos a ver um filme.", [], 4),
("estar_a", "Ты сейчас причёсываешься.", "Tu estás a pentear-te.", [], 4),
("estar_a", "Бруна сейчас слушает бразильскую музыку.", "A Bruna está a ouvir música brasileira.", [], 4),
("estar_a", "Сейчас Рут занимается, потому что завтра у неё экзамен.",
 "Agora, a Rute está a estudar, porque tem exame amanhã.", [], 4),
("estar_a", "Карлуш просыпается только в 7:00, поэтому он ещё спит.",
 "O Carlos só acorda às 7:00, por isso ele ainda está a dormir.", [], 4),
("estar_a", "Я сейчас читаю книгу.", "Eu estou a ler o livro.", [], 4),
("estar_a", "Твои двоюродные сёстры сейчас путешествуют по Испании.",
 "As tuas primas estão a viajar por Espanha.", [], 4),
("pres_regulares", "Вы приезжаете на работу на машине?", "Vocês vêm de carro para o trabalho?", [], 4),
("pres_regulares", "Даниэл и его друг умеют говорить по-португальски.",
 "O Daniel e o amigo sabem falar português.", [], 4),
("pres_regulares", "Извините, как сказать это слово по-португальски?",
 "Desculpe, como se diz esta palavra em português?", [], 4),
("pres_regulares", "Мы хотим работать летом.", "Nós queremos trabalhar no verão.", [], 4),
("pres_regulares", "Ты знаешь, где находится вокзал?",
 "Tu sabes onde fica a estação de comboios?", [], 4),
("pres_regulares", "Дочь Марты не может оставаться дома одна.",
 "A filha da Marta não pode ficar sozinha em casa.", [], 4),
("comparativo", "Лиссабон больше Коимбры.", "Lisboa é maior do que Coimbra.", [], 4),
("comparativo", "Эта книга лучше той.", "Este livro é melhor do que aquele.", [], 4),
("comparativo", "Ездить на автобусе медленнее, чем на метро.",
 "Andar de autocarro é menos rápido do que andar de metro.", [], 4),
("comparativo", "Жить в центре города дороже, чем в пригороде.",
 "Viver no centro da cidade é mais caro do que viver nos arredores.", [], 4),
("prep_movimento", "Мария едет в Портиман на отпуск.", "A Maria vai para Portimão passar férias.", [], 4),
("prep_movimento", "Мы идём в кино.", "Nós vamos ao cinema.", [], 4),
("prep_movimento", "Метро проходит по Авениде да Либердаде.", "O metro passa pela Avenida da Liberdade.", [], 4),
("transportes", "Мой брат ходит в университет пешком.", "O meu irmão vai a pé para a universidade.", [], 4),
("transportes", "Я езжу домой на велосипеде.", "Eu venho de bicicleta para casa.", [], 4),
("com_pronome", "Ты хочешь пойти со мной в кино?", "Tu queres vir ao cinema comigo?", [], 4),

# --- U5: погода, ir + inf, dar/fazer/trazer/pôr ---
("ir_inf", "Я выйду из дома в 9:00.", "Eu vou sair de casa às 9:00.", [], 5),
("ir_inf", "Ты будешь путешествовать следующим летом?", "Tu vais viajar no próximo verão?", [], 5),
("ir_inf", "Моя подруга купит синее платье.", "A minha amiga vai comprar um vestido azul.", [], 5),
("ir_inf", "Карен устроит пикник с семьёй.", "A Karen vai fazer um piquenique com a família.", [], 5),
("ir_inf", "Рафаэл снимет деньги в банкомате.", "O Rafael vai levantar dinheiro no multibanco.", [], 5),
("ir_inf", "Завтра будет дождь.", "Amanhã, vai chover.", [], 5),
("ir_inf", "Вы снимете квартиру на отпуск.", "Vocês vão arrendar um apartamento nas férias.", [], 5),
("ir_inf", "Она выпьет апельсиновый сок.", "Ela vai beber um sumo de laranja.", [], 5),
("ir_inf", "Мы посмотрим фильм в библиотеке.", "Nós vamos ver um filme na biblioteca.", [], 5),
("pres_regulares", "Я гуляю у моря.", "Eu dou um passeio à beira-mar.", [], 5),
("pres_regulares", "Дети кладут книги в шкаф.", "As crianças põem os livros no armário.", [], 5),
("pres_regulares", "Мы приносим спортивную одежду в рюкзаке.",
 "Nós trazemos a roupa de desporto na mochila.", [], 5),
("pres_regulares", "Ты кладёшь сахар в торт?", "Tu pões açúcar no bolo?", [], 5),
("pres_regulares", "Ученики делают упражнения дома?", "Os alunos fazem exercícios em casa?", [], 5),
("saber_conhecer", "Я не знаю Алентежу.", "Eu não conheço o Alentejo.", [], 5),
("saber_conhecer", "Он умеет готовить тайские блюда.", "Ele sabe cozinhar pratos tailandeses.", [], 5),
("saber_conhecer", "У меня не получается произнести это слово.", "Eu não consigo dizer esta palavra.", [], 5),
("saber_conhecer", "В библиотеке нельзя говорить по телефону.",
 "Na biblioteca, nós não podemos falar ao telemóvel.", [], 5),
("ha_desde", "Ясир живёт в Португалии два года.", "O Yasir vive em Portugal há dois anos.", [], 5),
("ha_desde", "Я работаю там уже пять лет.", "Eu já trabalho lá há cinco anos.", [], 5),
("ha_desde", "Инеш катается на лыжах с тех пор, как живёт в Швеции.",
 "A Inês pratica esqui desde que vive na Suécia.", [], 5),
("igualdade", "Франсишка такая же высокая, как её сестра.", "A Francisca é tão alta como a irmã.", [], 5),
("igualdade", "Я пью столько же воды, сколько ты.", "Eu bebo tanta água como tu.", [], 5),
("ci_pronome", "Сара даёт ему куртку.", "A Sara dá-lhe o casaco.", [], 5),
("ci_pronome", "Питер ей не звонит.", "O Peter não lhe telefona.", [], 5),
("ci_pronome", "Педру одалживает книгу брату.", "O Pedro empresta-lhe o livro.", [], 5),
("prep_pronome", "Можешь пойти в кино без меня.", "Podes ir ao cinema sem mim.", [], 5),
("prep_pronome", "Какой, по-твоему, лучший португальский пляж?",
 "Para ti, qual é a melhor praia portuguesa?", [], 5),
("em_meses", "Весной я люблю гулять по полям.", "Na primavera, gosto de passear pelos campos.", [], 5),
("em_meses", "Изабел поедет в путешествие в июне.", "A Isabel vai fazer uma viagem em junho.", [], 5),
("conectores", "Мариана устала, потому что много работает.", "A Mariana está cansada porque trabalha muito.", [], 5),
("conectores", "Мы можем выйти, но предпочитаем остаться дома.",
 "Nós podemos sair, mas preferimos ficar em casa.", [], 5),
("conectores", "Когда у меня есть свободное время, я занимаюсь спортом.",
 "Quando tenho tempo livre, faço exercício físico.", [], 5),

# --- U6: здоровье, императив, para/por ---
("pres_regulares", "У меня болит голова.", "Dói-me a cabeça.", [], 6),
("pres_regulares", "У них болят зубы.", "Doem-lhes os dentes.", [], 6),
("pres_regulares", "Я всегда принимаю обезболивающее, когда у меня эта проблема.",
 "Eu tomo sempre um analgésico quando tenho este problema.", [], 6),
("pres_regulares", "Родители Марии нервничают, поэтому плохо спят.",
 "Os pais da Maria andam nervosos, por isso dormem mal.", [], 6),
("pres_regulares", "Я прошу рецепт у своего врача.", "Eu peço uma receita ao meu médico.", [], 6),
("pres_regulares", "Сеньор Гедеш часто теряет ключи от дома.",
 "O Sr. Guedes perde as chaves de casa muitas vezes.", [], 6),
("imperativo", "Рита, ешьте более здоровую еду.", "Rita, coma alimentos mais saudáveis.", [], 6),
("imperativo", "Выключи телевизор. Я занимаюсь.", "Desliga a televisão. Estou a estudar.", [], 6),
("imperativo", "Закрой окно, очень холодно.", "Fecha a janela, pois está muito frio.", [], 6),
("imperativo", "Положите здесь ваш багаж, пожалуйста. (вежливо, к одному)", "Ponha a sua bagagem aqui, por favor.", [], 6),
("imperativo", "Говорите медленнее, пожалуйста.", "Fale mais devagar, por favor.", [], 6),
("imperativo", "Открой книгу на странице 12.", "Abre o livro na página 12.", [], 6),
("para_por", "Он много работает, чтобы больше зарабатывать.",
 "Ele trabalha muito para ganhar mais dinheiro.", [], 6),
("para_por", "Марта часто чихает из-за аллергии.", "A Marta espirra muito por ter alergias.", [], 6),
("para_por", "Мануэл звонит родителям, чтобы узнать, всё ли у них хорошо.",
 "O Manuel telefona aos pais para saber se eles estão bem.", [], 6),

# --- U7: праздники, indefinidos, tão/tanto ---
("tao_tanto", "Сегодня я такая голодная!", "Hoje, tenho tanta fome!", [], 7),
("tao_tanto", "Ты говоришь так тихо!", "Tu falas tão baixo!", [], 7),
("tao_tanto", "На Рождество съедается столько сладостей!", "No Natal, comem-se tantos doces!", [], 7),
("indefinidos", "Я никого не знаю на вечеринке.", "Eu não conheço ninguém na festa.", [], 7),
("indefinidos", "Жуан ничего не хочет есть.", "O João não quer comer nada.", [], 7),
("indefinidos", "Некоторые ученики уже говорят по-португальски.", "Alguns alunos já falam português.", [], 7),
("indefinidos", "Я езжу в Кабо-Верде каждый год.", "Vou para Cabo Verde todos os anos.", [], 7),
("marcadores_temp", "Я покупаю все подарки перед Рождеством.", "Eu compro todos os presentes antes do Natal.", [], 7),
("marcadores_temp", "Я пью кофе после обеда.", "Eu tomo um café depois do almoço.", [], 7),
("marcadores_temp", "Пока ты готовишь ужин, я накрываю на стол.",
 "Enquanto tu preparas o jantar, eu ponho a mesa.", [], 7),
("prep_tempo", "На Рождество мы обычно едим треску.", "No Natal, costumamos comer bacalhau.", [], 7),
("prep_tempo", "Тереза не работает по выходным.", "A Teresa não trabalha aos fins de semana.", [], 7),

# --- U8: PPS ---
("pps_regulares", "Я не работала на этой неделе.", "Eu não trabalhei esta semana.", [], 8),
("pps_regulares", "Вчера Тиагу надел куртку.", "Ontem, o Tiago vestiu o casaco.", [], 8),
("pps_regulares", "Два года назад я провела отпуск в Таиланде.",
 "Há dois anos, passei férias na Tailândia.", ["Há dois anos, eu passei férias na Tailândia."], 8),
("pps_regulares", "Им понравилось узнать Португалию.", "Eles gostaram de conhecer Portugal.", [], 8),
("pps_regulares", "Ты оставил карту в машине?", "Tu deixaste o mapa no carro?", [], 8),
("pps_regulares", "Сузана и Паулу переехали два месяца назад.",
 "A Susana e o Paulo mudaram de casa há dois meses.", [], 8),
("pps_regulares", "Вчера я забронировала билет на самолёт.", "Ontem, eu marquei a viagem de avião.", [], 8),
("pps_regulares", "Мои родители ещё не забронировали отель.",
 "Os meus pais ainda não reservaram o hotel.", [], 8),
("pps_regulares", "Мы с Карлой решили съездить в Кабо-Верде.",
 "Eu e a Carla decidimos viajar até Cabo Verde.", [], 8),
("pps_regulares", "Вчера мы прочитали очень интересный текст на уроке.",
 "Ontem, nós lemos um texto muito interessante na aula.", [], 8),
("pps_regulares", "Сегодня я прождала автобус целый час!", "Hoje, eu esperei uma hora pelo autocarro!", [], 8),
("pps_regulares", "Туристы остановились в отеле в центре города.",
 "Os turistas dormiram num hotel no centro da cidade.", [], 8),
("pps_regulares", "Вчера вечером я заплатила восемь евро за блюдо дня.",
 "Eu paguei oito euros pelo prato do dia.", [], 8),
("pps_irregulares", "В субботу вечером ты ходила в кино?", "No sábado à noite, tu foste ao cinema?", [], 8),
("pps_irregulares", "Прошлым летом мы были на Косте Висентине.",
 "No verão passado, nós estivemos na costa vicentina.", [], 8),
("pps_irregulares", "Сегодня утром у Анники была авария.", "Hoje de manhã, a Annika teve um acidente.", [], 8),
("pps_irregulares", "Вчера официант был очень любезен.", "Ontem, o empregado foi muito simpático.", [], 8),
("pps_irregulares", "В прошлом году мы ездили в Кабо-Верде.",
 "No ano passado, nós fomos a Cabo Verde.", [], 8),
("pps_irregulares", "Ты уже была в доме Сузаны?", "Tu já estiveste na casa da Susana?", [], 8),
("pps_irregulares", "У вас сегодня утром был урок португальского? (вы — несколько человек)",
 "Vocês tiveram aula de português hoje de manhã?", [], 8),
("pps_marcadores", "Мы уже были в Жерес.", "Nós já fomos ao Gerês.", [], 8),
("pps_marcadores", "Ты никогда не была у меня дома.", "Tu nunca estiveste em minha casa.", [], 8),
("pps_marcadores", "Тереза ещё не приехала в Кабо-Верде.", "A Teresa ainda não chegou a Cabo Verde.", [], 8),
("pps_marcadores", "В 2020 году я закончила бакалавриат.", "Em 2020, terminei a minha licenciatura.", [], 8),
("pps_marcadores", "Нет, я ещё не пробовала.", "Não, ainda não provei.", [], 8),
]
