# -*- coding: utf-8 -*-
"""Задания на подстановку и выбор. Предложения взяты из Português a Valer 1
(Caderno de exercícios) — ответы сверены с разделом Soluções."""

# (rule, предложение с ___, ответ, [альтернативы], юнит, подсказка)
GAPS = [
# --- предлоги de/em: страны и города (U1) ---
("de_em_paises", "A Augusta é ___ Camarões.", "dos", [], 1, "os Camarões"),
("de_em_paises", "A Sari e eu somos ___ Filipinas.", "das", [], 1, "as Filipinas"),
("de_em_paises", "O Philip é ___ Alemanha.", "da", [], 1, "a Alemanha"),
("de_em_paises", "O Kevin é ___ Chile.", "do", [], 1, "o Chile"),
("de_em_paises", "Nós somos ___ Países Baixos.", "dos", [], 1, "os Países Baixos"),
("de_em_paises", "O Xavier e a Helena são ___ Portugal.", "de", [], 1, "Portugal — без артикля"),
("de_em_paises", "A Margarida é ___ Braga.", "de", [], 1, "город без артикля"),
("de_em_paises", "O Zein é ___ Índia.", "da", [], 1, "a Índia"),
("de_em_paises", "A Carla mora ___ Luanda.", "em", [], 1, "город без артикля"),
("de_em_paises", "A Chiara mora ___ Berlim.", "em", [], 1, ""),
("de_em_paises", "A Mikaela é ___ Grécia.", "da", [], 1, "a Grécia"),
("de_em_paises", "O João mora ___ Brasil.", "no", [], 1, "o Brasil"),
("de_em_paises", "O Sr. Pereira mora ___ Rússia.", "na", [], 1, "a Rússia"),
("de_em_paises", "Eu sou de Portugal e moro ___ Porto.", "no", [], 1, "o Porto — исключение"),

# --- предлоги времени (U3) ---
("prep_tempo", "O comboio parte ___ nove e meia ___ manhã.", "às|da", [], 3, "часы + часть дня"),
("prep_tempo", "___ tarde, o meu pai dorme uma sesta.", "À", ["A"], 3, "часть дня"),
("prep_tempo", "Nós saímos de casa ___ meio-dia.", "ao", [], 3, ""),
("prep_tempo", "A aula começa ___ 15:30 e termina ___ 17:00.", "às|às", [], 3, ""),
("prep_tempo", "O Pedro vai ao cinema hoje ___ noite.", "à", [], 3, ""),
("prep_tempo", "___ manhã, nós costumamos correr antes do trabalho.", "De", [], 3, "часть дня без часа"),
("prep_tempo", "Eu tenho aulas de ioga ___ segundas-feiras.", "às", [], 3, "привычка"),
("prep_tempo", "___ próxima segunda-feira, vamos à Baixa tirar fotografias.", "Na", [], 3, "разовое событие"),
("prep_tempo", "___ domingo, vamos ao Porto.", "No", [], 3, "разовое событие"),
("prep_tempo", "A Paula trabalha ___ 9:00 ___ 18:00.", "das|às", [], 3, "с ... до ..."),

# --- предлоги движения (U4) ---
("prep_movimento", "Eu vou ___ casa e volto já.", "a", [], 4, "ненадолго"),
("prep_movimento", "Eu vou estudar ___ Coimbra.", "para", [], 4, "надолго"),
("prep_movimento", "A minha mãe passa ___ minha casa muitas vezes.", "pela", [], 4, "маршрут"),
("prep_movimento", "Eles vão ___ esta rua porque é mais rápido.", "por", [], 4, "маршрут"),
("prep_movimento", "O André vai agora ___ o hotel porque está muito cansado.", "para", [], 4, ""),
("prep_movimento", "Hoje, a Rita passa ___ casa da avó.", "pela", [], 4, ""),
("prep_movimento", "Eu vou ___ farmácia comprar um analgésico.", "à", [], 4, "ненадолго + a farmácia"),
("prep_movimento", "A Keshu vai ___ a China quando terminar o curso.", "para", [], 4, ""),

# --- para / por (U6) ---
("para_por", "O Greg vai ___ o trabalho de metro.", "para", [], 6, "пункт назначения"),
("para_por", "Eu ando cansado ___ ter muito trabalho.", "por", [], 6, "причина"),
("para_por", "Como há muito trânsito, temos de ir ___ esta rua.", "por", [], 6, "маршрут"),
("para_por", "O Manuel telefona aos pais ___ saber se eles estão bem.", "para", [], 6, "цель"),
("para_por", "Nós devemos chegar ao Porto ___ 20:00.", "pelas", [], 6, "приблизительное время"),
("para_por", "O telemóvel tem garantia ___ um ano.", "por", [], 6, "срок"),
("para_por", "___ mim, viajar de comboio é mais interessante do que viajar de avião.", "Para", [], 6, "мнение"),

# --- em: месяцы и времена года (U5) ---
("em_meses", "Normalmente, ___ janeiro, está mais frio em Portugal.", "em", [], 5, "месяц"),
("em_meses", "Nós gostamos de tirar fotografias ___ outono.", "no", [], 5, "время года"),
("em_meses", "Este ano, a Micaela vai trabalhar ___ verão.", "no", [], 5, ""),
("em_meses", "___ Páscoa, as crianças comem ovos de chocolate.", "Na", [], 5, "праздник"),
("em_meses", "___ Ano Novo, as pessoas bebem champanhe.", "No", [], 5, ""),
("em_meses", "A Isabel vai fazer uma viagem ___ junho.", "em", [], 5, ""),

# --- há / desde (U5) ---
("ha_desde", "O Ben estuda português ___ três meses.", "há", [], 5, "отрезок времени"),
("ha_desde", "A Inês pratica esqui ___ que vive na Suécia.", "desde", [], 5, "точка отсчёта"),
("ha_desde", "Nós moramos aqui ___ o nosso casamento.", "desde", [], 5, ""),
("ha_desde", "Eu já trabalho lá ___ cinco anos.", "há", [], 5, ""),
("ha_desde", "A Olívia faz campismo ___ criança.", "desde", [], 5, ""),

# --- tão / tanto (U5, U7) ---
("igualdade", "No Algarve, não faz ___ frio como no Minho.", "tanto", [], 5, "существительное м. р."),
("igualdade", "Nós não temos ___ livros como vocês.", "tantos", [], 5, ""),
("igualdade", "A cidade onde eu moro é ___ grande como a cidade onde tu moras.", "tão", [], 5, "прилагательное"),
("igualdade", "A Teresa não tem ___ tempo livre como eu.", "tanto", [], 5, ""),
("igualdade", "Eu bebo ___ água como tu.", "tanta", [], 5, "существительное ж. р."),
("tao_tanto", "Hoje, tenho ___ fome!", "tanta", [], 7, ""),
("tao_tanto", "Tu falas ___ baixo!", "tão", [], 7, "наречие"),
("tao_tanto", "A Cátia trabalha ___ horas!", "tantas", [], 7, ""),
("tao_tanto", "Tu bebes o café com ___ açúcar!", "tanto", [], 7, ""),

# --- местоимения (U4, U5) ---
("com_pronome", "Carlos, eu vou ___ ao hospital. (com + tu)", "contigo", [], 4, ""),
("com_pronome", "Ela vai ___ ao oculista. (com + eu)", "comigo", [], 4, ""),
("com_pronome", "A Bruna estuda ___? (com + nós)", "connosco", [], 4, ""),
("com_pronome", "Dr. Rui, o Klaus vai ___ à reunião. (com + o senhor)", "consigo", [], 4, ""),
("ci_pronome", "A Ana envia uma mensagem às primas. → A Ana envia-___ uma mensagem.", "lhes", [], 5, ""),
("ci_pronome", "Os atletas telefonam ao treinador. → Os atletas telefonam-___.", "lhe", [], 5, ""),
("ci_pronome", "Nós emprestamos o caderno ao Paulo. → Nós emprestamos-___ o caderno.", "lhe", [], 5, ""),
("ci_pronome", "O Duarte conta uma história aos filhos. → O Duarte conta-___ uma história.", "lhes", [], 5, ""),
("prep_pronome", "Para quem é este livro? (eu) → Para ___.", "mim", [], 5, ""),
("prep_pronome", "Para quem é o bilhete? (tu) → Para ___.", "ti", [], 5, ""),
("prep_pronome", "Dra. Anabela, qual é a melhor proposta para ___?", "si", [], 5, ""),

# --- маркеры и союзы ---
("conectores", "A Mariana está cansada ___ trabalha muito.", "porque", [], 5, "причина"),
("conectores", "A Luísa vive junto ao mar, ___ não gosta de peixe.", "mas", [], 5, "противопоставление"),
("conectores", "___ está sol, vamos correr à beira-mar.", "Quando", [], 5, "время"),
("marcadores_temp", "A minha mãe termina o relatório ___ o meu pai cozinha.", "enquanto", [], 7, "одновременно"),
("marcadores_temp", "Eu compro todos os presentes ___ Natal.", "antes do", [], 7, "до + слияние"),
("marcadores_temp", "___ a fadista Mariza canta, o público aplaude.", "Quando", [], 7, ""),
("marcadores_temp", "___ tu preparas o jantar, eu ponho a mesa.", "Enquanto", [], 7, ""),

# --- indefinidos (U7) ---
("indefinidos", "Eu não conheço ___ na festa.", "ninguém", [], 7, "о людях"),
("indefinidos", "Vou para Cabo Verde ___ os anos.", "todos", [], 7, ""),
("indefinidos", "O João não quer comer ___.", "nada", [], 7, "о вещах"),
("indefinidos", "Está ___ na entrada do prédio.", "alguém", [], 7, ""),
("indefinidos", "Ainda não tenho ___ fome.", "muita", [], 7, ""),

# --- expressões de lugar (U2) ---
("lugar", "O livro está ao lado ___ estojo.", "do", [], 2, "de + o"),
("lugar", "O sapato está debaixo ___ mesa.", "da", [], 2, "de + a"),
("lugar", "O gato está em frente ___ janela.", "da", [], 2, ""),
("lugar", "O gato está atrás ___ computador.", "do", [], 2, ""),
("lugar", "O gato está dentro ___ mochila.", "da", [], 2, ""),
]

# (rule, предложение с ___, правильный, [неправильные], юнит, подсказка)
MC = [
("ser_estar", "A Yudith ___ da Venezuela.", "é", ["está"], 2, "происхождение"),
("ser_estar", "Agora, a Rute ___ a estudar, porque tem exame amanhã.", "está", ["é"], 4, ""),
("ser_estar", "O António ___ arquiteto.", "é", ["está"], 2, "профессия"),
("ser_estar", "As irmãs da Margarida ___ no Algarve.", "estão", ["são"], 2, "место"),
("ser_estar", "A Valentina ___ sempre alegre.", "está", ["é"], 2, "состояние"),
("ser_estar", "Estes jogadores de basquetebol ___ americanos.", "são", ["estão"], 2, ""),
("pres_regulares", "O Eduardo e o João ___ nos Açores.", "vivem", ["vives", "vivemos"], 2, ""),
("pres_regulares", "Eu ___ os filhos da Ana.", "conheço", ["conhece", "conheces"], 2, ""),
("pres_regulares", "Nós ___ produtos biológicos.", "comemos", ["comem", "come"], 2, ""),
("pres_regulares", "Tu ___ na ecopista.", "corres", ["corre", "corremos"], 2, ""),
("pres_regulares", "O escritor ___ poemas muito bonitos.", "escreve", ["escrevem", "escrevo"], 2, ""),
("pres_regulares", "Eles raramente ___ televisão.", "veem", ["vemos", "vê"], 3, ""),
("pres_regulares", "A Raquel ___ um livro antes de dormir.", "lê", ["leio", "leem"], 3, ""),
("pres_regulares", "O professor ___ da sala quando a aula termina.", "sai", ["saem", "saio"], 3, ""),
("pres_regulares", "A Miriam e a filha ___ ao parque ao final da tarde.", "vão", ["veem", "vai"], 3, ""),
("pres_regulares", "A Gisela ___ até mais tarde ao fim de semana.", "dorme", ["dormes", "durmo"], 6, ""),
("pres_regulares", "O cliente ___ a conta ao empregado.", "pede", ["dá", "peço"], 6, ""),
("pres_regulares", "O Klaus ___ a gramática para as aulas de português.", "traz", ["pode", "trago"], 6, ""),
("saber_conhecer", "O Peter e a namorada ___ os meus pais.", "conhecem", ["sabem"], 6, "знакомы с людьми"),
("saber_conhecer", "O Daniel ___ falar francês, inglês e português muito bem.", "consegue", ["conhece"], 6, "способность"),
("saber_conhecer", "Tu ___ a que horas passa o autocarro?", "sabes", ["podes"], 6, "знать факт"),
("saber_conhecer", "As crianças não ___ nadar quando estão doentes.", "podem", ["sabem"], 6, "запрет"),
("saber_conhecer", "Eu não ___ ir ao ginásio porque tenho uma reunião.", "posso", ["sei"], 6, ""),
("transportes", "Eu vou ___ autocarro das 8:00.", "no", ["de"], 4, "конкретный автобус"),
("transportes", "O Juan vai ___ mota para o trabalho.", "de", ["na"], 4, "транспорт вообще"),
("transportes", "O meu irmão vai ___ pé para a universidade.", "a", ["de"], 4, "исключение"),
("transportes", "Eu e a Carolina vamos para Faro ___ comboio Alfa Pendular.", "no", ["de"], 4, "конкретный поезд"),
("prep_movimento", "Nós vamos ___ cinema.", "ao", ["pelo"], 4, ""),
("prep_movimento", "O metro passa ___ Avenida da Liberdade.", "pela", ["para a"], 4, ""),
("prep_movimento", "A Elisa vai ___ hospital. Ela é enfermeira.", "para o", ["ao"], 4, "надолго — работа"),
("prep_movimento", "O Luís vai ___ supermercado fazer compras.", "ao", ["para o"], 4, "ненадолго"),
("comparativo", "Lisboa é ___ do que Coimbra.", "maior", ["mais grande"], 4, "исключение"),
("comparativo", "Este livro é ___ do que aquele.", "melhor", ["mais bom"], 4, "исключение"),
("comparativo", "A nova temporada é ___ do que a segunda.", "pior", ["mais má"], 4, "исключение"),
("prep_tempo", "___ sábado, bebemos uma cerveja. O que achas?", "No", ["Ao"], 3, "разовое"),
("prep_tempo", "O restaurante fecha ___ domingos.", "aos", ["nos"], 3, "привычка"),
("prep_tempo", "A Raquel sai de casa ___ manhã.", "de", ["à"], 3, "часть дня без часа"),
("prep_tempo", "A professora chega à escola ___ oito e meia ___ manhã.", "às ... da", ["das ... na"], 3, ""),
("prep_tempo", "Hoje, chego à escola antes das três ___ tarde.", "da", ["de"], 3, "после указания часа"),
("prep_tempo", "___ terças-feiras, temos aulas de PLE.", "Às", ["A"], 7, "привычка"),
("prep_tempo", "O ginásio está fechado ___ domingos.", "aos", ["nos"], 7, ""),
("prep_tempo", "Este ano, o Carnaval é ___ fevereiro.", "em", ["no"], 7, "месяц"),
("pps_irregulares", "No verão passado, nós ___ no Brasil.", "estivemos", ["estive", "esteve"], 8, ""),
("pps_irregulares", "Ontem, a Madison ___ aulas até às seis da tarde.", "teve", ["tive", "tiveram"], 8, ""),
("pps_irregulares", "Nós ___ a Cabo Verde no ano passado.", "fomos", ["foram", "fui"], 8, ""),
("pps_irregulares", "Na semana passada, o professor faltou, porque ___ doente.", "esteve", ["estive", "estiveste"], 8, ""),
("pps_irregulares", "A Madalena perdeu o porta-moedas, por isso ___ à esquadra da Polícia.", "foi", ["fui", "foste"], 8, ""),
("pps_regulares", "O Jannik e o irmão ___ português há dois anos.", "aprenderam", ["aprendeu", "aprendeste"], 8, ""),
("pps_regulares", "Eu e a Carmen ___ cinco anos no Peru.", "vivemos", ["viveram", "vivi"], 8, ""),
("pps_regulares", "O Sr. António ___ uma sopa ao almoço.", "comeu", ["comi", "comemos"], 8, ""),
("pps_regulares", "Tu e o Pablo já ___ a carta do banco?", "receberam", ["recebeste", "recebemos"], 8, ""),
("pps_regulares", "Eu enviei uma mensagem à Simone, mas ela não ___.", "respondeu", ["respondi", "respondeste"], 8, ""),
("pps_regulares", "No ano passado, nós ___ um destino de férias exótico.", "escolhemos", ["escolheram", "escolheu"], 8, ""),
("pps_regulares", "Ontem, o meu avô não ___ o telefone, porque foi passear.", "atendeu", ["atendi", "atendeste"], 8, ""),
("indefinidos", "Vês ___ no jardim?", "alguém", ["algum"], 7, ""),
("indefinidos", "A Susana tem ___ mapa?", "algum", ["alguma"], 7, ""),
("indefinidos", "Este copo está partido. Dá-me ___, por favor?", "outro", ["outra"], 7, ""),
("indefinidos", "Esta festa tem ___ convidados.", "muitos", ["nenhuns"], 7, ""),
("possessivos", "Mãe, onde estão ___ óculos?", "os meus", ["o meu"], 2, ""),
("possessivos", "Dra. Vera, esta pasta é ___?", "sua", ["tua"], 2, "формальное обращение"),
("imperativo", "[você] ___ (pôr) a sua bagagem aqui.", "Ponha", ["Põe"], 6, "формальный"),
("imperativo", "[tu] ___ (fechar) a janela, pois está muito frio.", "Fecha", ["Feche"], 6, "неформальный"),
("imperativo", "[você] ___ (imprimir) este relatório, por favor.", "Imprima", ["Imprime"], 6, ""),
("imperativo", "[tu] ___ (ir) buscar as crianças à escola.", "Vai", ["Vá"], 6, ""),
("ha_desde", "A Maria faz visitas guiadas ___ que trabalha na Casa da Música.", "desde", ["há"], 5, ""),
("ha_desde", "A atleta olímpica pratica natação ___ mais de dez anos.", "há", ["desde"], 5, ""),

("artigos", "A Rita tem ___ presente para a amiga.", "um", ["o"], 7, "первое упоминание"),
("artigos", "A Rita tem um presente. ___ presente é um livro.", "O", ["Um"], 7, "уже известен"),
("artigos", "Eu peço ___ sopa. A sopa está quente.", "uma", ["a"], 3, "первое упоминание"),
("artigos", "Eu peço uma sopa. ___ sopa está deliciosa.", "A", ["Uma"], 3, "уже известна"),
("artigos", "A Ana mora num apartamento. ___ apartamento tem uma varanda.", "O", ["Um"], 4, "уже известен"),
("artigos", "O apartamento tem ___ varanda. A varanda é grande.", "uma", ["a"], 4, "первое упоминание"),
("artigos", "Eu compro ___ livro. O livro é sobre Portugal.", "um", ["o"], 2, "первое упоминание"),
("artigos", "Nós temos um professor novo. ___ professor é do Porto.", "O", ["Um"], 2, "уже известен"),
]
