# -*- coding: utf-8 -*-
"""Структура уроков: что вводится в каждом юните Português a Valer 1.
Источник — Índice + грамматические рамки Caderno de exercícios."""

# unit: тема, лексика, глаголы (по типам), грамматика, предлоги/артикли
UNITS = [
 dict(n=1, pt="Olá! Eu sou a Ana.", ru="Знакомство",
      lex=["apresentação","nacionalidades","profissões"],
      verbs_reg=["morar","estudar","trabalhar","falar","gostar","jogar"],
      verbs_irr=["ser","ter"], verbs_refl=["chamar-se"],
      conj=["-ar"],
      gram=["ser_estar","artigos","reflexos","pres_regulares"],
      prep=["de_em_paises"],
      extra="числа до 50, определённые артикли o/a/os/as"),
 dict(n=2, pt="A tua amiga é muito simpática!", ru="Семья и характер",
      lex=["família","carácter","lugar","objetos"],
      verbs_reg=["viver","comer","escrever","beber","correr","entender","aprender","receber","responder"],
      verbs_irr=["estar","conhecer","adormecer","oferecer","descer"], verbs_refl=[],
      conj=["-er"],
      gram=["ser_estar","possessivos","lugar","pres_regulares"],
      prep=["lugar","contracoes"],
      extra="неопределённые артикли um/uma, числа до 160"),
 dict(n=3, pt="Vamos almoçar?", ru="Еда и распорядок дня",
      lex=["alimentação","bebidas","doces","refeições","restaurante","horas","frequência"],
      verbs_reg=["decidir","partir","abrir","permitir","dividir","imprimir"],
      verbs_irr=["vestir","despir","preferir","sentir","repetir","conseguir","ver","ler","ouvir","ir","sair"],
      verbs_refl=["levantar-se","deitar-se","sentar-se","vestir-se","lavar-se","sentir-se","esquecer-se"],
      conj=["-ir"],
      gram=["pres_regulares","reflexos","prep_tempo","contracoes"],
      prep=["prep_tempo"],
      extra="часы, выражения частотности"),
 dict(n=4, pt="A vossa casa fica longe?", ru="Дом, город, транспорт",
      lex=["casa","cidade","direções","transportes"],
      verbs_reg=["apanhar","virar","atravessar","ficar","arrumar"],
      verbs_irr=["vir","poder","querer","dizer","saber"], verbs_refl=[],
      conj=["-ar","-er","-ir"],
      gram=["ter_de","estar_a","comparativo","com_pronome"],
      prep=["prep_movimento","transportes"],
      extra="числа до 1000"),
 dict(n=5, pt="Como vai estar o tempo?", ru="Погода, месяцы, одежда",
      lex=["meses","estações","tempo","roupa"],
      verbs_reg=["dançar","viajar","comprar"],
      verbs_irr=["dar","fazer","trazer","pôr"], verbs_refl=[],
      conj=["-ar","-er","-ir"],
      gram=["ir_inf","saber_conhecer","ha_desde","igualdade","ci_pronome","conectores"],
      prep=["em_meses","prep_pronome"],
      extra="даты, сравнение равенства"),
 dict(n=6, pt="Estás melhor?", ru="Тело и здоровье",
      lex=["corpo","saúde"],
      verbs_reg=["tomar"],
      verbs_irr=["pedir","perder","dormir","doer"], verbs_refl=["sentir-se"],
      conj=["-ar","-er","-ir"],
      gram=["imperativo","pres_regulares","saber_conhecer"],
      prep=["para_por"],
      extra="повторение неправильных глаголов"),
 dict(n=7, pt="Quantos anos fazes?", ru="Праздники и приглашения",
      lex=["festas","mesa"],
      verbs_reg=["convidar","telefonar","emprestar","entregar","contar","enviar","mostrar"],
      verbs_irr=["oferecer","agradecer","devolver"], verbs_refl=[],
      conj=["-ar","-er","-ir"],
      gram=["tao_tanto","indefinidos","marcadores_temp","imperativo"],
      prep=["prep_tempo"],
      extra="повторение presente и императива"),
 dict(n=8, pt="Passei férias em Cabo Verde.", ru="Отпуск и прошедшее время",
      lex=["viagens","tempos livres","marcadores"],
      verbs_reg=["visitar","pagar","cozinhar","estacionar","tirar","preparar","adorar","deixar",
                 "mudar","esperar","entrar","usar","marcar","reservar","alugar","nadar","chegar","acordar"],
      verbs_irr=["ir","ser","estar","ter"], verbs_refl=["divertir-se"],
      conj=["-ar","-er","-ir"],
      gram=["pps_regulares","pps_irregulares","pps_marcadores"],
      prep=["prep_tempo","prep_movimento"],
      extra="маркеры прошедшего: ontem, já, nunca, ainda não"),
]

# ---------------------------------------------------------------------------
# «Глагол дня»: одна и та же фраза во всех лицах и во всех пройденных временах.
# (инфинитив, дополнение PT, дополнение RU, рус. инфинитив,
#  наст. формы [я,ты,она,мы,они], прош. ж.р., прош. мн., continuous?, юнит)
VERB_DRILLS = [
 ("morar", "em Lisboa", "в Лиссабоне", "жить",
  ["живу","живёшь","живёт","живём","живут"], "жила", "жили", False, 1),
 ("trabalhar", "no hospital", "в больнице", "работать",
  ["работаю","работаешь","работает","работаем","работают"], "работала", "работали", True, 1),
 ("falar", "português", "по-португальски", "говорить",
  ["говорю","говоришь","говорит","говорим","говорят"], "говорила", "говорили", True, 1),
 ("ter", "aula de português", "урок португальского", "иметь",
  ["имею","имеешь","имеет","имеем","имеют"], "имела", "имели", False, 1),
 ("comer", "peixe ao jantar", "рыбу на ужин", "есть",
  ["ем","ешь","ест","едим","едят"], "ела", "ели", True, 2),
 ("viver", "perto do mar", "у моря", "жить",
  ["живу","живёшь","живёт","живём","живут"], "жила", "жили", True, 2),
 ("escrever", "uma mensagem", "сообщение", "писать",
  ["пишу","пишешь","пишет","пишем","пишут"], "писала", "писали", True, 2),
 ("beber", "café de manhã", "кофе по утрам", "пить",
  ["пью","пьёшь","пьёт","пьём","пьют"], "пила", "пили", True, 2),
 ("preferir", "comida vegetariana", "вегетарианскую еду", "предпочитать",
  ["предпочитаю","предпочитаешь","предпочитает","предпочитаем","предпочитают"],
  "предпочитала", "предпочитали", False, 3),
 ("sair", "de casa às 8:00", "из дома в 8:00", "выходить",
  ["выхожу","выходишь","выходит","выходим","выходят"], "вышла", "вышли", True, 3),
 ("levantar-se", "às sete horas", "в семь часов", "вставать",
  ["встаю","встаёшь","встаёт","встаём","встают"], "встала", "встали", True, 3),
 ("ler", "o jornal", "газету", "читать",
  ["читаю","читаешь","читает","читаем","читают"], "читала", "читали", True, 3),
 ("querer", "um café", "кофе", "хотеть",
  ["хочу","хочешь","хочет","хотим","хотят"], "хотела", "хотели", False, 4),
 ("poder", "ajudar", "оказать помощь", "мочь",
  ["могу","можешь","может","можем","могут"], "могла", "могли", False, 4),
 ("apanhar", "o autocarro", "автобус", "садиться на",
  ["сажусь на","садишься на","садится на","садимся на","садятся на"],
  "села на", "сели на", True, 4),
 ("fazer", "exercício físico", "зарядку", "делать",
  ["делаю","делаешь","делает","делаем","делают"], "делала", "делали", True, 5),
 ("viajar", "para o Porto", "в Порту", "ездить",
  ["езжу","ездишь","ездит","ездим","ездят"], "ездила", "ездили", True, 5),
 ("pôr", "os livros na mochila", "книги в рюкзак", "класть",
  ["кладу","кладёшь","кладёт","кладём","кладут"], "положила", "положили", True, 5),
 ("dormir", "oito horas", "восемь часов", "спать",
  ["сплю","спишь","спит","спим","спят"], "спала", "спали", True, 6),
 ("pedir", "a conta", "счёт", "просить",
  ["прошу","просишь","просит","просим","просят"], "попросила", "попросили", True, 6),
 ("tomar", "um analgésico", "обезболивающее", "принимать",
  ["принимаю","принимаешь","принимает","принимаем","принимают"],
  "приняла", "приняли", True, 6),
 ("convidar", "os amigos", "друзей", "приглашать",
  ["приглашаю","приглашаешь","приглашает","приглашаем","приглашают"],
  "пригласила", "пригласили", True, 7),
 ("oferecer", "um presente", "подарок", "дарить",
  ["дарю","даришь","дарит","дарим","дарят"], "подарила", "подарили", True, 7),
 ("telefonar", "à mãe", "маме", "звонить",
  ["звоню","звонишь","звонит","звоним","звонят"], "звонила", "звонили", True, 7),
 ("visitar", "um museu", "музей", "посещать",
  ["посещаю","посещаешь","посещает","посещаем","посещают"], "посетила", "посетили", True, 8),
 ("escolher", "um destino", "направление", "выбирать",
  ["выбираю","выбираешь","выбирает","выбираем","выбирают"], "выбрала", "выбрали", True, 8),
 ("decidir", "ficar em casa", "остаться дома", "решать",
  ["решаю","решаешь","решает","решаем","решают"], "решила", "решили", True, 8),
 ("ir", "à praia", "на пляж", "ходить",
  ["хожу","ходишь","ходит","ходим","ходят"], "ходила", "ходили", False, 8),
 ("estar", "no Algarve", "в Алгарве", "быть",
  ["я в","ты в","она в","мы в","они в"], "была", "были", False, 8),
]

# особые формы будущего (вместо «буду + инф.»)
RU_FUT = {
    "poder":    ["смогу", "сможешь", "сможет", "сможем", "смогут"],
    "querer":   ["захочу", "захочешь", "захочет", "захотим", "захотят"],
    "apanhar":  ["сяду на", "сядешь на", "сядет на", "сядем на", "сядут на"],
    "decidir":  ["решу", "решишь", "решит", "решим", "решат"],
    "oferecer": ["подарю", "подаришь", "подарит", "подарим", "подарят"],
    "convidar": ["приглашу", "пригласишь", "пригласит", "пригласим", "пригласят"],
    "visitar":  ["посещу", "посетишь", "посетит", "посетим", "посетят"],
    "escolher": ["выберу", "выберешь", "выберет", "выберем", "выберут"],
    "tomar":    ["приму", "примешь", "примет", "примем", "примут"],
    "pedir":    ["попрошу", "попросишь", "попросит", "попросим", "попросят"],
    "pôr":      ["положу", "положишь", "положит", "положим", "положат"],
    "sair":     ["выйду", "выйдешь", "выйдет", "выйдем", "выйдут"],
    "levantar-se": ["встану", "встанешь", "встанет", "встанем", "встанут"],
}

SUBJ_RU = ["Я", "Ты", "Она", "Мы", "Они"]
SUBJ_PT = ["Eu", "Tu", "Ela", "Nós", "Eles"]
FUT_RU  = ["буду", "будешь", "будет", "будем", "будут"]
