# -*- coding: utf-8 -*-
"""Мини-истории: 3–4 фразы из лексики юнита, собираются пофразно переводом с русского.
Все конструкции и слова — из пройденного материала книги."""

# (unit, заголовок RU, [(ru, pt, [альтернативы])])
STORIES = [
 (1, "Новая коллега", [
   ("Это {n.ru}, она {nac.ru}.", "Esta é a {n.pt}, ela é {nac.pt}.", ["Esta é a {n.pt}. Ela é {nac.pt}."]),
   ("Она {prof.ru} и работает {prof.lru}.", "Ela é {prof.pt} e trabalha {prof.lpt}.", ["É {prof.pt} e trabalha {prof.lpt}."]),
   ("Ей {id.pt} лет, и сейчас она живёт в {cid.ru}.", "Ela tem {id.pt} anos e agora mora em {cid.pt}.", ["Tem {id.pt} anos e agora mora em {cid.pt}."]),
   ("Она говорит {nac.lr} и по-португальски.", "Ela fala {nac.lp} e português.", ["Fala {nac.lp} e português."]),
 ], dict(
   n=[dict(pt="Elena", ru="Элена"), dict(pt="Marta", ru="Марта"), dict(pt="Sofia", ru="София"), dict(pt="Ingrid", ru="Ингрид")],
   nac=[dict(pt="italiana", ru="итальянка", lp="italiano", lr="по-итальянски"),
        dict(pt="espanhola", ru="испанка", lp="espanhol", lr="по-испански"),
        dict(pt="francesa", ru="француженка", lp="francês", lr="по-французски"),
        dict(pt="alemã", ru="немка", lp="alemão", lr="по-немецки")],
   id=[dict(pt="37"), dict(pt="29"), dict(pt="45")],
   cid=[dict(pt="Lisboa", ru="Лиссабоне"), dict(pt="Braga", ru="Браге"), dict(pt="Coimbra", ru="Коимбре")],
   prof=[dict(pt="médica", ru="врач", lpt="num hospital", lru="в больнице"),
         dict(pt="cabeleireira", ru="парикмахер", lpt="num cabeleireiro", lru="в парикмахерской"),
         dict(pt="professora", ru="учительница", lpt="numa escola", lru="в школе"),
         dict(pt="enfermeira", ru="медсестра", lpt="num hospital", lru="в больнице"),
         dict(pt="jornalista", ru="журналистка", lpt="num jornal", lru="в газете")],
 )),
 (1, "Я и мой сосед", [
   ("Меня зовут Андрей, я из России.", "Eu chamo-me Andrei e sou da Rússia.", ["Chamo-me Andrei e sou da Rússia.", "Eu chamo-me Andrei, sou da Rússia."]),
   ("Я живу в Браге и работаю в школе.", "Eu moro em Braga e trabalho numa escola.", ["Moro em Braga e trabalho numa escola."]),
   ("Мой сосед — механик.", "O meu vizinho é mecânico.", []),
   ("Он из Кабо-Верде.", "Ele é de Cabo Verde.", []),
 ]),
 (2, "Семья Беатриш", [
   ("У Беатриш большая семья.", "A Beatriz tem uma família grande.", []),
   ("Её мама — учительница, а папа — инженер.", "A mãe dela é professora e o pai é engenheiro.", ["A mãe dela é professora e o pai dela é engenheiro."]),
   ("Бабушка и дедушка живут в Вила-Реал.", "Os avós vivem em Vila Real.", ["A avó e o avô vivem em Vila Real."]),
   ("Все они очень приятные.", "Eles são todos muito simpáticos.", ["Todos são muito simpáticos.", "São todos muito simpáticos."]),
 ]),
 (2, "Кот в комнате", [
   ("Кот в рюкзаке.", "O gato está dentro da mochila.", []),
   ("Книга рядом с пеналом.", "O livro está ao lado do estojo.", []),
   ("Компьютер на столе.", "O computador está em cima da mesa.", []),
   ("А туфли — под стулом.", "E os sapatos estão debaixo da cadeira.", ["Os sapatos estão debaixo da cadeira."]),
 ]),
 (3, "Утро Жорже", [
   ("Жорже встаёт в семь часов.", "O Jorge levanta-se às sete horas.", ["O Jorge levanta-se às 7:00."]),
   ("На завтрак он ест хлопья с молоком.", "Ao pequeno-almoço, ele come cereais com leite.", ["Ao pequeno-almoço, come cereais com leite."]),
   ("Он выходит из дома в восемь и садится на метро.", "Ele sai de casa às oito e apanha o metro.", ["Sai de casa às oito e apanha o metro.", "Ele sai de casa às 8:00 e apanha o metro."]),
   ("Вечером он читает книгу и рано ложится.", "À noite, ele lê um livro e deita-se cedo.", ["À noite, lê um livro e deita-se cedo."]),
 ]),
 (3, "В ресторане", [
   ("Мы обедаем на террасе.", "Nós almoçamos na esplanada.", ["Almoçamos na esplanada."]),
   ("Я предпочитаю рыбу, а Паулу ест курицу.", "Eu prefiro peixe e o Paulo come frango.", []),
   ("Мы пьём апельсиновый сок.", "Nós bebemos sumo de laranja.", ["Bebemos sumo de laranja."]),
   ("На десерт мы заказываем два паштела де ната.", "Para sobremesa, pedimos dois pastéis de nata.", ["De sobremesa, pedimos dois pastéis de nata."]),
 ]),
 (4, "Наша квартира", [
   ("Мы живём в квартире в центре города.", "Nós moramos num apartamento no centro da cidade.", ["Moramos num apartamento no centro da cidade."]),
   ("В квартире две комнаты, кухня и балкон.", "O apartamento tem dois quartos, uma cozinha e uma varanda.", []),
   ("Рядом с домом есть булочная и аптека.", "Ao lado do prédio, há uma padaria e uma farmácia.", ["Perto do prédio, há uma padaria e uma farmácia."]),
   ("Супермаркет далеко, поэтому мы ездим на машине.", "O supermercado fica longe, por isso vamos de carro.", ["O supermercado é longe, por isso vamos de carro."]),
 ]),
 (4, "Дорога на работу", [
   ("Грег ездит на работу на метро.", "O Greg vai para o trabalho de metro.", []),
   ("Сегодня метро не работает.", "Hoje, o metro não funciona.", []),
   ("Поэтому ему надо сесть на автобус.", "Por isso, ele tem de apanhar o autocarro.", ["Por isso, tem de apanhar o autocarro."]),
   ("Автобус проходит по центральному проспекту.", "O autocarro passa pela avenida central.", ["O autocarro passa pela Avenida Central."]),
 ]),
 (5, "Планы на выходные", [
   ("В субботу будет солнечно.", "No sábado, vai estar sol.", []),
   ("Мы устроим пикник на пляже.", "Nós vamos fazer um piquenique na praia.", ["Vamos fazer um piquenique na praia."]),
   ("Я принесу бутерброды и фрукты.", "Eu vou trazer sandes e fruta.", ["Vou trazer sandes e fruta."]),
   ("Вечером мы посмотрим фильм дома.", "À noite, vamos ver um filme em casa.", []),
 ]),
 (5, "Зимой", [
   ("Зимой в Португалии идёт дождь.", "No inverno, chove em Portugal.", []),
   ("Я надеваю пальто и шарф.", "Eu visto o casaco e ponho o cachecol.", ["Visto o casaco e ponho o cachecol."]),
   ("На Серра-да-Эштрела может идти снег.", "Na Serra da Estrela, pode nevar.", []),
   ("Поэтому мы приносим тёплую одежду.", "Por isso, trazemos roupa quente.", ["Por isso, nós trazemos roupa quente."]),
 ]),
 (6, "Педру болен", [
   ("{n.ru} чувствует себя плохо.", "O {n.pt} sente-se mal.", []),
   ("У него болит {dor.ru}, и у него {sin.ru}.", "{dor.pt} e {sin.pt}.", ["{dor.pt} e ele {sin.pt}."]),
   ("Он принимает {rem.ru} и пьёт чай.", "Ele toma {rem.pt} e bebe chá.", ["Toma {rem.pt} e bebe chá."]),
   ("Сегодня ему надо спать больше.", "Hoje, ele tem de dormir mais.", ["Hoje, tem de dormir mais."]),
 ], dict(
   n=[dict(pt="Pedro", ru="Педру"), dict(pt="Rui", ru="Руй"), dict(pt="Miguel", ru="Мигел")],
   dor=[dict(pt="Dói-lhe a cabeça", ru="голова"), dict(pt="Dói-lhe a garganta", ru="горло"),
        dict(pt="Dói-lhe a barriga", ru="живот"), dict(pt="Doem-lhe as costas", ru="спина")],
   sin=[dict(pt="tem tosse", ru="кашель"), dict(pt="tem febre", ru="температура"),
        dict(pt="está com gripe", ru="грипп")],
   rem=[dict(pt="um analgésico", ru="обезболивающее"), dict(pt="um medicamento", ru="лекарство")],
 )),
 (7, "День рождения", [
   ("В субботу у Риты день рождения.", "No sábado, é o aniversário da Rita.", []),
   ("Она приглашает всех друзей.", "Ela convida todos os amigos.", ["Convida todos os amigos."]),
   ("Мы дарим ей книгу и цветы.", "Nós oferecemos-lhe um livro e flores.", ["Oferecemos-lhe um livro e flores."]),
   ("На столе столько сладостей!", "Há tantos doces em cima da mesa!", ["Em cima da mesa, há tantos doces!"]),
 ]),
 (8, "Отпуск в Кабо-Верде", [
   ("В прошлом году я провела отпуск в Кабо-Верде.", "No ano passado, passei férias em Cabo Verde.", ["No ano passado, eu passei férias em Cabo Verde."]),
   ("Я плавала каждый день и посетила рынок.", "Nadei todos os dias e visitei o mercado.", ["Eu nadei todos os dias e visitei o mercado."]),
   ("Мы остановились в отеле в центре города.", "Ficámos num hotel no centro da cidade.", ["Nós ficámos num hotel no centro da cidade."]),
   ("Отпуск был замечательный!", "As férias foram fantásticas!", ["As férias foram muito boas!"]),
 ]),
 (8, "Вчерашний день", [
   ("Вчера я встала в восемь.", "Ontem, levantei-me às oito.", ["Ontem, eu levantei-me às oito.", "Ontem, levantei-me às 8:00."]),
   ("Утром я работала в библиотеке.", "De manhã, trabalhei na biblioteca.", ["De manhã, eu trabalhei na biblioteca."]),
   ("Потом я пообедала с Аной в ресторане.", "Depois, almocei com a Ana num restaurante.", ["Depois, eu almocei com a Ana num restaurante."]),
   ("Вечером мы сходили в кино.", "À noite, fomos ao cinema.", ["À noite, nós fomos ao cinema."]),
 ]),
 (4, "Квартира Аны · um → o", [
   ("Ана живёт в квартире в Лиссабоне.", "A Ana mora num apartamento em Lisboa.", []),
   ("В квартире есть кухня и балкон.", "O apartamento tem uma cozinha e uma varanda.", []),
   ("Кухня маленькая, но балкон большой.", "A cozinha é pequena, mas a varanda é grande.", []),
   ("Утром Ана пьёт кофе на балконе.", "De manhã, a Ana bebe café na varanda.", ["De manhã, a Ana bebe um café na varanda."]),
 ]),
 (7, "Подарок · um → o", [
   ("У Риты есть подарок для подруги.", "A Rita tem um presente para a amiga.", []),
   ("Подарок — это книга.", "O presente é um livro.", []),
   ("Книга очень интересная.", "O livro é muito interessante.", []),
   ("Подруга обожает книгу!", "A amiga adora o livro!", []),
 ]),
 (3, "Обед · um → o", [
   ("Я заказываю суп и стакан вина.", "Eu peço uma sopa e um copo de vinho.", ["Peço uma sopa e um copo de vinho."]),
   ("Суп очень горячий.", "A sopa está muito quente.", []),
   ("Вино белое и холодное.", "O vinho é branco e está frio.", ["O vinho é branco e frio."]),
   ("Официант приносит счёт.", "O empregado traz a conta.", []),
 ]),
 (1, "Гость из другой страны", [
   ("Его зовут {n.pt}.", "O nome dele é {n.pt}.", ["Ele chama-se {n.pt}."]),
   ("Он из {pais.ru}, и ему {id.pt} лет.", "Ele é {pais.pt} e tem {id.pt} anos.", []),
   ("Он {prof.ru}.", "Ele é {prof.pt}.", ["É {prof.pt}."]),
   ("Сейчас он живёт в {cid.ru}.", "Agora, ele mora em {cid.pt}.", ["Agora, mora em {cid.pt}."]),
 ], dict(
   n=[dict(pt="Andrei"), dict(pt="Tiago"), dict(pt="Pablo"), dict(pt="John")],
   pais=[dict(pt="da Rússia", ru="России"), dict(pt="do Brasil", ru="Бразилии"),
         dict(pt="de Espanha", ru="Испании"), dict(pt="dos Estados Unidos", ru="США")],
   id=[dict(pt="53"), dict(pt="28"), dict(pt="34")],
   prof=[dict(pt="tenista", ru="теннисист"), dict(pt="engenheiro", ru="инженер"),
         dict(pt="ator", ru="актёр"), dict(pt="cantor", ru="певец"), dict(pt="arquiteto", ru="архитектор")],
   cid=[dict(pt="Braga", ru="Браге"), dict(pt="Lisboa", ru="Лиссабоне"), dict(pt="Faro", ru="Фару")],
 )),
 (2, "Лифт не работает", [
   ("Лифт не работает.", "O elevador não funciona.", []),
   ("Поэтому сеньор Перейра спускается по лестнице пешком.", "Por isso, o Sr. Pereira desce as escadas a pé.", []),
   ("Он живёт на четвёртом этаже.", "Ele mora no quarto andar.", ["Mora no quarto andar."]),
   ("Вечером его дети засыпают до девяти.", "À noite, os filhos dele adormecem antes das nove.", ["À noite, os seus filhos adormecem antes das nove."]),
 ]),
 (3, "Счёт на троих", [
   ("Мы ужинаем в ресторане втроём.", "Nós jantamos num restaurante os três.", ["Jantamos num restaurante os três."]),
   ("Официант приносит счёт.", "O empregado traz a conta.", []),
   ("Я делю счёт на троих.", "Eu divido a conta pelos três.", ["Divido a conta pelos três."]),
   ("По десять евро с каждого.", "São dez euros a cada um.", []),
 ]),
 (4, "Дорога в кино", [
   ("Где находится кинотеатр?", "Onde fica o cinema?", []),
   ("Поверни на следующей улице налево.", "Vira na próxima rua à esquerda.", []),
   ("Потом — на первой направо.", "Depois, na primeira à direita.", ["Depois, vira na primeira à direita."]),
   ("Это близко: пять минут пешком.", "É perto: são cinco minutos a pé.", ["É perto. São cinco minutos a pé."]),
 ]),
 (5, "Спортсменка", [
   ("Атлетка занимается плаванием больше десяти лет.", "A atleta pratica natação há mais de dez anos.", []),
   ("Она играет в теннис шесть месяцев.", "Ela joga ténis há seis meses.", ["Joga ténis há seis meses."]),
   ("Она бегает каждый день, когда хорошая погода.", "Ela corre todos os dias quando está bom tempo.", ["Corre todos os dias quando está bom tempo."]),
   ("Зимой она предпочитает заниматься дома.", "No inverno, ela prefere fazer exercício em casa.", ["No inverno, prefere fazer exercício em casa."]),
 ]),
 (6, "На приёме у доктора Сары", [
   ("Педру всегда усталый, но никогда не занимается спортом.", "O Pedro está sempre cansado, mas nunca faz exercício físico.", []),
   ("У него бессонница почти каждый день.", "Ele tem insónias quase todos os dias.", ["Tem insónias quase todos os dias."]),
   ("У него часто болит голова, и он принимает обезболивающее.", "Dói-lhe a cabeça frequentemente e ele toma um analgésico.", []),
   ("Доктор Сара говорит: лучше сделать анализы.", "A Dra. Sara diz: é melhor fazer análises.", ["A doutora diz que é melhor fazer análises."]),
 ]),
 (7, "Рождество", [
   ("На Рождество мы обычно едим треску.", "No Natal, costumamos comer bacalhau.", []),
   ("На столе также есть болу-рей.", "Em cima da mesa, também há bolo-rei.", ["Também há bolo-rei em cima da mesa."]),
   ("Дети открывают подарки в полночь.", "As crianças abrem os presentes à meia-noite.", []),
   ("Вся семья вместе, и все очень довольные.", "A família está toda junta e todos estão muito contentes.", ["Toda a família está junta e todos estão contentes."]),
 ]),
 (8, "Путешествие Саймона", [
   ("Саймон проснулся в семь часов и принял душ.", "O Simon acordou às sete horas e tomou banho.", []),
   ("Потом он собрал чемодан и вызвал такси.", "Depois, preparou a mala e chamou um táxi.", ["Depois, ele preparou a mala e chamou um táxi."]),
   ("В аэропорту он стоял в очереди на регистрацию.", "No aeroporto, esteve na fila para fazer o check-in.", ["No aeroporto, ele esteve na fila para o check-in."]),
   ("Когда он прилетел, он арендовал машину и приехал в отель в два часа.",
    "Quando chegou, alugou um carro e chegou ao hotel às duas.", ["Quando chegou, ele alugou um carro e chegou ao hotel às duas horas."]),
 ]),
 (5, "Спортивная неделя", [
   ("Во вторник я играю в футбол с друзьями.", "Na terça-feira, jogo futebol com os amigos.", ["À terça-feira, jogo futebol com os amigos."]),
   ("В четверг мы занимаемся плаванием в бассейне.", "Na quinta-feira, praticamos natação na piscina.", ["À quinta-feira, praticamos natação na piscina."]),
   ("По выходным я катаюсь на велосипеде у моря.", "Ao fim de semana, ando de bicicleta à beira-mar.", []),
   ("Спорт полезнее, чем телевизор!", "O desporto é melhor do que a televisão!", ["O desporto é mais saudável do que a televisão!"]),
 ]),
 (3, "Неделя Аны", [
   ("В понедельник и среду Ана работает в библиотеке.", "Na segunda e na quarta-feira, a Ana trabalha na biblioteca.", ["À segunda e à quarta-feira, a Ana trabalha na biblioteca."]),
   ("В пятницу вечером она ужинает с подругами.", "Na sexta-feira à noite, ela janta com as amigas.", ["À sexta-feira à noite, janta com as amigas."]),
   ("В субботу утром она ходит на рынок.", "No sábado de manhã, ela vai ao mercado.", ["Ao sábado de manhã, vai ao mercado."]),
   ("Воскресенье — её любимый день: она отдыхает.", "O domingo é o dia preferido dela: ela descansa.", ["O domingo é o seu dia preferido: descansa."]),
 ]),
]