# -*- coding: utf-8 -*-
"""Темы лексического блока: имя, иконка, какие theme-ключи vocab входят,
связанные диалоги и юнит историй для «разговорной практики дня»."""

THEMES = [
 dict(key="cores", ru="Цвета", icon="🎨", vt=["cores"], dlg=["roupa"], su=None),
 dict(key="corpo", ru="Тело", icon="🦵", vt=["corpo"], dlg=["medico"], su=6),
 dict(key="saúde", ru="Боль и здоровье", icon="🤒", vt=["saúde","médicos"], dlg=["farmacia","medico","farmacia2"], su=6),
 dict(key="tempo", ru="Погода и времена года", icon="⛅", vt=["tempo","estações"], dlg=["planos"], su=5),
 dict(key="roupa", ru="Одежда и обувь", icon="👗", vt=["roupa"], dlg=["roupa"], su=5),
 dict(key="mesa", ru="Стол и посуда", icon="🍽", vt=["mesa"], dlg=["restaurante"], su=3),
 dict(key="comida", ru="Еда", icon="🥗", vt=["alimentação","doces","refeições","pratos"], dlg=["mercado","restaurante","supermercado"], su=3),
 dict(key="bebidas", ru="Напитки", icon="☕", vt=["bebidas"], dlg=["cafe"], su=3),
 dict(key="casa", ru="Дом и мебель", icon="🛋", vt=["casa","mobiliário"], dlg=["supermercado"], su=4),
 dict(key="cidade", ru="Город и магазины", icon="🏙", vt=["cidade","direções"], dlg=["direcoes","supermercado"], su=4),
 dict(key="transportes", ru="Транспорт", icon="🚆", vt=["transportes"], dlg=["bilheteira","aluguer"], su=4),
 dict(key="família", ru="Семья и характер", icon="👨‍👩‍👧", vt=["família","carácter","aparência","civil"], dlg=["familia"], su=2),
 dict(key="profissões", ru="Профессии", icon="🧑‍⚕️", vt=["profissões"], dlg=["conhecer"], su=1),
 dict(key="nacionalidades", ru="Страны и национальности", icon="🌍", vt=["nacionalidades","apresentação"], dlg=["conhecer"], su=1),
 dict(key="festas", ru="Праздники и день рождения", icon="🎂", vt=["festas","pratos"], dlg=["convite"], su=7),
 dict(key="viagens", ru="Путешествия", icon="✈️", vt=["viagens","tempos livres"], dlg=["hotel","viagem"], su=8),
 dict(key="desporto", ru="Спорт и свободное время", icon="⚽", vt=["desporto","tempos livres"], dlg=["tempo_livre"], su=5),
 dict(key="cultura", ru="Культура и выходы", icon="🎭", vt=["cultura"], dlg=["convite"], su=4),
 dict(key="calendário", ru="Дни, месяцы, время", icon="📅", vt=["dias","meses","horas","frequência","marcadores","ordinais"], dlg=["bilheteira","cabeleireiro"], su=3),
 dict(key="aula", ru="На уроке", icon="✏️", vt=["aula","objetos"], dlg=["conhecer"], su=1),
]

# антонимы (юнит 7: sinónimos e antónimos + пары из учебника)
ANTONYMS = [
 ("adorar", "detestar", "обожать ↔ ненавидеть"),
 ("quente", "frio", "горячий ↔ холодный"),
 ("depressa", "devagar", "быстро ↔ медленно"),
 ("marcar", "desmarcar", "назначить ↔ отменить"),
 ("contente", "triste", "довольный ↔ грустный"),
 ("grande", "pequeno", "большой ↔ маленький"),
 ("alto", "baixo", "высокий ↔ низкий"),
 ("bom", "mau", "хороший ↔ плохой"),
 ("caro", "barato", "дорогой ↔ дешёвый"),
 ("perto", "longe", "близко ↔ далеко"),
 ("cedo", "tarde", "рано ↔ поздно"),
 ("sempre", "nunca", "всегда ↔ никогда"),
 ("muito", "pouco", "много ↔ мало"),
 ("novo", "velho", "новый ↔ старый"),
 ("magro", "gordo", "худой ↔ полный"),
 ("fácil", "difícil", "лёгкий ↔ трудный"),
 ("aberto", "fechado", "открытый ↔ закрытый"),
 ("primeiro", "último", "первый ↔ последний"),
 ("vestir", "despir", "надеть ↔ снять"),
 ("subir", "descer", "подниматься ↔ спускаться"),
 ("chegar", "partir", "прибывать ↔ уезжать"),
 ("comprar", "vender", "покупать ↔ продавать"),
 ("perguntar", "responder", "спрашивать ↔ отвечать"),
 ("acordar", "adormecer", "просыпаться ↔ засыпать"),
]
