# -*- coding: utf-8 -*-
"""Картинный словарь (45 страниц фото): тематическая лексика.
Формат: (pt, артикль|None, ru, тема)"""

VOCAB2 = [
# ---------- corpo: снаружи ----------
("cabelo","o","волосы","corpo2"), ("testa","a","лоб","corpo2"),
("sobrancelhas","as","брови","corpo2"), ("olhos","os","глаза","corpo2"),
("nariz","o","нос","corpo2"), ("orelha","a","ухо (снаружи)","corpo2"),
("lábios","os","губы","corpo2"), ("boca","a","рот","corpo2"),
("dentes","os","зубы","corpo2"), ("queixo","o","подбородок","corpo2"),
("bochecha","a","щека","corpo2"), ("pescoço","o","шея","corpo2"),
("ombro","o","плечо","corpo2"), ("braço","o","рука (от плеча)","corpo2"),
("cotovelo","o","локоть","corpo2"), ("pulso","o","запястье","corpo2"),
("mão","a","кисть руки","corpo2"), ("dedos","os","пальцы","corpo2"),
("unhas","as","ногти","corpo2"), ("peito","o","грудь","corpo2"),
("seio","o","грудь (женская)","corpo2"), ("costas","as","спина","corpo2"),
("tronco","o","туловище","corpo2"), ("cintura","a","талия","corpo2"),
("barriga","a","живот","corpo2"), ("anca","a","бедро (сустав)","corpo2"),
("coxa","a","бедро","corpo2"), ("joelho","o","колено","corpo2"),
("perna","a","нога","corpo2"), ("tornozelo","o","лодыжка","corpo2"),
("pé","o","ступня","corpo2"), ("traseiro","o","ягодицы","corpo2"),
# ---------- corpo: внутри ----------
("coração","o","сердце","corpo_dentro"), ("pulmão","o","лёгкое","corpo_dentro"),
("estômago","o","желудок","corpo_dentro"), ("fígado","o","печень","corpo_dentro"),
("rins","os","почки","corpo_dentro"), ("intestino","o","кишечник","corpo_dentro"),
("bexiga","a","мочевой пузырь","corpo_dentro"), ("pâncreas","o","поджелудочная","corpo_dentro"),
("costelas","as","рёбра","corpo_dentro"), ("caixa torácica","a","грудная клетка","corpo_dentro"),
("abdómen","o","живот, брюшная полость","corpo_dentro"),
# ---------- saúde ----------
("ter dores de cabeça",None,"болит голова","saude2"),
("ter dores de dentes",None,"болят зубы","saude2"),
("ter dores de ouvidos",None,"болят уши","saude2"),
("ter dores de estômago",None,"болит желудок","saude2"),
("ter dores de costas",None,"болит спина","saude2"),
("ter dores de garganta",None,"болит горло","saude2"),
("ter febre",None,"температура","saude2"),
("estar constipado",None,"простудиться","saude2"),
("estar com gripe",None,"болеть гриппом","saude2"),
("tossir",None,"кашлять","saude2"), ("espirrar",None,"чихать","saude2"),
("assoar-se",None,"сморкаться","saude2"),
("sarampo","o","корь","saude2"), ("papeira","a","свинка","saude2"),
("partir um braço",None,"сломать руку","saude2"),
("estar doente",None,"болеть, быть больным","saude2"),
("estar bem de saúde",None,"быть здоровым","saude2"),
("fazer um tratamento",None,"проходить лечение","saude2"),
("ir ao médico",None,"идти к врачу","saude2"),
("ficar internado",None,"лечь в больницу","saude2"),
("seringa","a","шприц","saude2"), ("penso","o","пластырь, повязка","saude2"),
# ---------- vestuário senhora ----------
("vestido","o","платье","roupa2"), ("saia","a","юбка","roupa2"),
("blusa","a","блузка","roupa2"), ("camisa","a","рубашка","roupa2"),
("T-shirt","a","футболка","roupa2"), ("top","o","топ","roupa2"),
("calças","as","брюки","roupa2"), ("jeans","os","джинсы","roupa2"),
("calças de ganga","as","джинсы","roupa2"), ("calções","os","шорты","roupa2"),
("bermudas","as","бермуды","roupa2"), ("casaco","o","пиджак, куртка","roupa2"),
("blusão","o","ветровка, короткая куртка","roupa2"),
("camisola de gola alta","a","водолазка","roupa2"),
("fato de banho","o","купальник","roupa2"), ("avental","o","фартук","roupa2"),
("meias","as","носки, колготки","roupa2"), ("cuequinhas","as","трусики","roupa2"),
("sandálias","as","сандалии","roupa2"), ("sapatos rasos","os","туфли без каблука","roupa2"),
("sapatos de salto alto","os","туфли на каблуке","roupa2"),
("luvas","as","перчатки","roupa2"), ("lenço","o","платок","roupa2"),
("chapéu","o","шляпа","roupa2"), ("óculos de sol","os","солнечные очки","roupa2"),
("carteira","a","сумочка, кошелёк","roupa2"), ("cinto","o","ремень","roupa2"),
("anel","o","кольцо","roupa2"), ("colar","o","колье, бусы","roupa2"),
("pulseira","a","браслет","roupa2"), ("brincos","os","серьги","roupa2"),
("écharpe","a","шарф, палантин","roupa2"),
# ---------- vestuário homem ----------
("fato","o","костюм","roupa_homem"), ("gravata","a","галстук","roupa_homem"),
("sweatshirt","a","свитшот","roupa_homem"), ("pulôver","o","пуловер","roupa_homem"),
("colete","o","жилет","roupa_homem"), ("anoraque","o","анорак","roupa_homem"),
("gabardina","a","плащ","roupa_homem"), ("casaco comprido","o","пальто","roupa_homem"),
("fato de treino","o","спортивный костюм","roupa_homem"),
("calção de banho","o","плавки","roupa_homem"),
("boxers","os","боксеры","roupa_homem"), ("cuecas","as","трусы","roupa_homem"),
("slip","o","слипы","roupa_homem"), ("sapatilhas","as","кроссовки","roupa_homem"),
("ténis","os","кроссовки","roupa_homem"), ("botas","as","ботинки, сапоги","roupa_homem"),
("cachecol","o","шарф","roupa_homem"), ("boné","o","кепка","roupa_homem"),
("relógio","o","часы (наручные)","roupa_homem"),
("barbatanas","as","ласты","roupa_homem"),
# ---------- rotina diária ----------
("acordar",None,"просыпаться","rotina"), ("levantar-se",None,"вставать","rotina"),
("tomar um duche",None,"принимать душ","rotina"), ("tomar banho",None,"принимать ванну","rotina"),
("fazer a barba",None,"бриться","rotina"), ("lavar os dentes",None,"чистить зубы","rotina"),
("vestir-se",None,"одеваться","rotina"), ("calçar-se",None,"обуваться","rotina"),
("pentear-se",None,"причёсываться","rotina"),
("tomar o pequeno-almoço",None,"завтракать","rotina"),
("preparar-se para sair",None,"собираться выходить","rotina"),
("sair de casa",None,"выходить из дома","rotina"),
("chegar ao trabalho",None,"приходить на работу","rotina"),
("fazer ginástica",None,"заниматься спортом","rotina"),
("almoçar",None,"обедать","rotina"), ("lanchar",None,"полдничать","rotina"),
("voltar para casa",None,"возвращаться домой","rotina"),
("ir às compras",None,"ходить за покупками","rotina"),
("jantar",None,"ужинать","rotina"), ("ver televisão",None,"смотреть телевизор","rotina"),
("deitar-se",None,"ложиться спать","rotina"), ("ressonar",None,"храпеть","rotina"),
# ---------- família ----------
("primo","o","двоюродный брат","familia2"), ("prima","a","двоюродная сестра","familia2"),
("tio","o","дядя","familia2"), ("tia","a","тётя","familia2"),
("avô","o","дедушка","familia2"), ("avó","a","бабушка","familia2"),
("avós","os","бабушка с дедушкой","familia2"),
("neto","o","внук","familia2"), ("neta","a","внучка","familia2"),
("sogro","o","свёкор, тесть","familia2"), ("sogra","a","свекровь, тёща","familia2"),
("cunhado","o","шурин, деверь","familia2"), ("cunhada","a","золовка, невестка","familia2"),
("esposa","a","супруга","familia2"), ("marido","o","муж","familia2"),
("sobrinho","o","племянник","familia2"), ("sobrinha","a","племянница","familia2"),
("genro","o","зять","familia2"), ("nora","a","невестка","familia2"),
("bebé","o","младенец","familia2"),

# ---------- casa: комнаты ----------
("sótão","o","чердак","casa2"), ("rés do chão","o","первый этаж","casa2"),
("primeiro andar","o","второй этаж","casa2"), ("escadas","as","лестница","casa2"),
("hall de entrada","o","прихожая","casa2"), ("sala de estar","a","гостиная","casa2"),
("sala de jantar","a","столовая","casa2"), ("cozinha","a","кухня","casa2"),
("despensa","a","кладовая","casa2"), ("quarto","o","спальня","casa2"),
("casa de banho","a","ванная","casa2"), ("escritório","o","кабинет","casa2"),
("garagem","a","гараж","casa2"), ("varanda","a","балкон","casa2"),
("telhado","o","крыша","casa2"), ("chaminé","a","дымоход","casa2"),
("porta de entrada","a","входная дверь","casa2"), ("vedação","a","забор","casa2"),
("portão","o","ворота","casa2"), ("relva","a","газон","casa2"),
("bater à porta",None,"стучать в дверь","casa2"),
("tocar à campainha",None,"звонить в звонок","casa2"),
("subir as escadas",None,"подниматься по лестнице","casa2"),
("descer as escadas",None,"спускаться по лестнице","casa2"),
# ---------- sala de estar ----------
("sofá","o","диван","sala"), ("cadeirão","o","кресло","sala"),
("estante","a","стеллаж","sala"), ("lareira","a","камин","sala"),
("candeeiro","o","торшер, лампа","sala"), ("quadro","o","картина","sala"),
("vela","a","свеча","sala"), ("tapete","o","ковёр","sala"),
("almofada","a","подушка (диванная)","sala"), ("televisor","o","телевизор","sala"),
("coluna de som","a","колонка","sala"), ("leitor de DVD","o","DVD-плеер","sala"),
("revista","a","журнал","sala"), ("jornal","o","газета","sala"),
("telefone","o","телефон","sala"),
# ---------- sala de jantar ----------
("aparador","o","буфет","jantar"), ("moldura","a","рамка","jantar"),
("castiçal","o","подсвечник","jantar"), ("relógio de parede","o","настенные часы","jantar"),
("jarra","a","ваза","jantar"), ("tomada","a","розетка","jantar"),
("toalha","a","скатерть","jantar"), ("guardanapo","o","салфетка","jantar"),
("chávena","a","чашка","jantar"), ("pires","o","блюдце","jantar"),
("caneca","a","кружка","jantar"), ("taça","a","пиала, бокал","jantar"),
("bule do chá","o","чайник заварочный","jantar"), ("açúcar","o","сахар","jantar"),
("sal","o","соль","jantar"), ("pimenta","a","перец","jantar"),
("doce","o","варенье, сладкое","jantar"), ("bolacha","a","печенье","jantar"),
("sandes","a","бутерброд","jantar"), ("fatia de bolo","a","кусок торта","jantar"),
("barrar o pão com manteiga",None,"намазать хлеб маслом","jantar"),
# ---------- cozinha ----------
("fogão","o","плита","cozinha2"), ("frigorífico","o","холодильник","cozinha2"),
("armário de cozinha","o","кухонный шкаф","cozinha2"), ("gaveta","a","ящик","cozinha2"),
("banca da louça","a","мойка","cozinha2"), ("torneira","a","кран","cozinha2"),
("panela","a","кастрюля","cozinha2"), ("tacho","o","сотейник","cozinha2"),
("frigideira","a","сковорода","cozinha2"), ("chaleira","a","чайник","cozinha2"),
("tabuleiro","o","поднос","cozinha2"), ("louça","a","посуда","cozinha2"),
("prato","o","тарелка","cozinha2"), ("copo","o","стакан","cozinha2"),
("colher","a","ложка","cozinha2"), ("garfo","o","вилка","cozinha2"),
("faca","a","нож","cozinha2"), ("abre-latas","o","консервный нож","cozinha2"),
("rolo da massa","o","скалка","cozinha2"), ("detergente","o","моющее средство","cozinha2"),
("esfregona","a","швабра","cozinha2"), ("vassoura","a","метла","cozinha2"),
("pá do lixo","a","совок","cozinha2"), ("balde do lixo","o","мусорное ведро","cozinha2"),
("pano do pó","o","тряпка для пыли","cozinha2"),
("ferro de engomar","o","утюг","cozinha2"),
("máquina de lavar roupa","a","стиральная машина","cozinha2"),
("lavar a loiça",None,"мыть посуду","cozinha2"),
("passar a ferro",None,"гладить","cozinha2"),
("varrer o chão",None,"подметать пол","cozinha2"),
("aspirar o chão",None,"пылесосить","cozinha2"),
("levar o lixo",None,"выносить мусор","cozinha2"),
# ---------- quarto ----------
("cama","a","кровать","quarto2"), ("lençol","o","простыня","quarto2"),
("cobertor","o","одеяло","quarto2"), ("almofada (de dormir)","a","подушка","quarto2"),
("mesa de cabeceira","a","тумбочка","quarto2"), ("roupeiro","o","шкаф для одежды","quarto2"),
("cabide","o","вешалка","quarto2"), ("cómoda","a","комод","quarto2"),
("despertador","o","будильник","quarto2"), ("interruptor","o","выключатель","quarto2"),
("pijama","o","пижама","quarto2"), ("roupão","o","халат","quarto2"),
("frasco de perfume","o","флакон духов","quarto2"),
("escova do cabelo","a","расчёска","quarto2"), ("malas","as","чемоданы","quarto2"),
("ursinho de peluche","o","плюшевый мишка","quarto2"),
("fazer a cama",None,"заправлять кровать","quarto2"),
("arrumar o quarto",None,"убирать комнату","quarto2"),
# ---------- casa de banho ----------
("espelho","o","зеркало","banho"), ("lavatório","o","раковина","banho"),
("banheira","a","ванна","banho"), ("chuveiro","o","душ","banho"),
("cortina","a","занавеска","banho"), ("sanita","a","унитаз","banho"),
("autoclismo","o","сливной бачок","banho"), ("toalha (de banho)","a","полотенце","banho"),
("toalheiro","o","полотенцесушитель","banho"), ("sabonete","o","мыло","banho"),
("champô","o","шампунь","banho"), ("gel de banho","o","гель для душа","banho"),
("esponja","a","губка","banho"), ("pasta de dentes","a","зубная паста","banho"),
("escova de dentes","a","зубная щётка","banho"), ("pente","o","гребень","banho"),
("balança","a","весы","banho"), ("papel higiénico","o","туалетная бумага","banho"),
("lavar-se",None,"мыться","banho"), ("pesar-se",None,"взвешиваться","banho"),
("arranjar-se",None,"приводить себя в порядок","banho"),
# ---------- escritório ----------
("computador","o","компьютер","escritorio"), ("teclado","o","клавиатура","escritorio"),
("rato","o","мышь","escritorio"), ("secretária","a","письменный стол","escritorio"),
("prateleira","a","полка","escritorio"), ("pasta de arquivo","a","папка","escritorio"),
("bloco de notas","o","блокнот","escritorio"), ("caneta","a","ручка","escritorio"),
("esferográfica","a","шариковая ручка","escritorio"), ("lápis","o","карандаш","escritorio"),
("lápis de cor","os","цветные карандаши","escritorio"), ("borracha","a","ластик","escritorio"),
("afia-lápis","o","точилка","escritorio"), ("régua","a","линейка","escritorio"),
("cesto dos papéis","o","корзина для бумаг","escritorio"),
("aquecedor elétrico","o","обогреватель","escritorio"),
("rádio","o","радио","escritorio"), ("cabo elétrico","o","провод","escritorio"),
("escrever uma carta",None,"писать письмо","escritorio"),
("navegar na Internet",None,"сидеть в интернете","escritorio"),
("enviar um e-mail",None,"отправить письмо","escritorio"),
# ---------- jardim ----------
("árvore","a","дерево","jardim"), ("arbusto","o","куст","jardim"),
("flor","a","цветок","jardim"), ("margaridas","as","ромашки","jardim"),
("túlipas","as","тюльпаны","jardim"), ("amores-perfeitos","os","анютины глазки","jardim"),
("malmequer","o","маргаритка","jardim"), ("jardineiras","as","цветочные ящики","jardim"),
("vaso","o","горшок","jardim"), ("planta","a","растение","jardim"),
("mangueira","a","шланг","jardim"), ("regar",None,"поливать","jardim"),
("abelha","a","пчела","jardim"), ("borboleta","a","бабочка","jardim"),
("mosca","a","муха","jardim"), ("caracol","o","улитка","jardim"),
("pessegueiro","o","персиковое дерево","jardim"), ("pereira","a","груша (дерево)","jardim"),
("laranjeira","a","апельсиновое дерево","jardim"),
("árvores de fruto","as","фруктовые деревья","jardim"),
("botas de borracha","as","резиновые сапоги","jardim"),
("chapéu de palha","o","соломенная шляпа","jardim"),
("escorrega","o","горка","jardim"), ("pátio","o","дворик","jardim"),

# ---------- serviços, lugares e direções ----------
("parque","o","парк","cidade2"), ("esquadra da polícia","a","полицейский участок","cidade2"),
("paragem de autocarro","a","автобусная остановка","cidade2"),
("escola de música","a","музыкальная школа","cidade2"),
("escola básica","a","начальная школа","cidade2"),
("escola secundária","a","старшая школа","cidade2"),
("pousada","a","гостиница, постоялый двор","cidade2"),
("catedral","a","собор","cidade2"), ("torre da igreja","a","колокольня","cidade2"),
("museu","o","музей","cidade2"), ("parque infantil","o","детская площадка","cidade2"),
("supermercado","o","супермаркет","cidade2"), ("bar","o","бар","cidade2"),
("florista","a","цветочный магазин","cidade2"), ("fonte","a","фонтан","cidade2"),
("cabeleireiro","o","парикмахерская","cidade2"),
("centro comercial","o","торговый центр","cidade2"),
("ginásio","o","спортзал","cidade2"), ("hospital","o","больница","cidade2"),
("ir em frente",None,"идти прямо","cidade2"),
("virar à direita",None,"повернуть направо","cidade2"),
("virar à esquerda",None,"повернуть налево","cidade2"),
("na esquina",None,"на углу","cidade2"),
("atravessar a passadeira",None,"перейти по переходу","cidade2"),
# ---------- preposições de lugar ----------
("em cima de",None,"на, сверху","lugar2"), ("dentro de",None,"внутри","lugar2"),
("à frente de",None,"перед","lugar2"), ("entre",None,"между","lugar2"),
("atrás de",None,"за, позади","lugar2"), ("debaixo de",None,"под","lugar2"),
("ao lado de",None,"рядом с","lugar2"), ("fora de",None,"снаружи","lugar2"),
("do lado esquerdo",None,"слева","lugar2"), ("do lado direito",None,"справа","lugar2"),
("perto de",None,"близко к","lugar2"), ("longe de",None,"далеко от","lugar2"),
# ---------- escola / trabalho ----------
("quadro (da escola)","o","доска","escola2"), ("giz","o","мел","escola2"),
("mochila","a","рюкзак","escola2"), ("caderno","o","тетрадь","escola2"),
("professora","a","учительница","escola2"), ("aluno","o","ученик","escola2"),
("recreio","o","перемена","escola2"), ("ginásio da escola","o","спортзал школы","escola2"),
("notas","as","оценки","escola2"), ("arquivo","o","архив","escola2"),
("recados","os","сообщения, записки","escola2"),
("fotocopiadora","a","копир","escola2"), ("impressora","a","принтер","escola2"),
("reunião","a","совещание","escola2"), ("chefe","o","начальник","escola2"),
# ---------- oficina / transportes ----------
("bomba de gasolina","a","заправка","oficina"), ("oficina","a","автомастерская","oficina"),
("mecânico","o","механик","oficina"), ("pneu","o","шина","oficina"),
("motor","o","двигатель","oficina"), ("volante","o","руль","oficina"),
("chave","a","ключ","oficina"), ("gasolina","a","бензин","oficina"),
("carro","o","машина","oficina"), ("camião","o","грузовик","oficina"),
("mota","a","мотоцикл","oficina"), ("bicicleta","a","велосипед","oficina"),
# ---------- supermercado ----------
("carrinho de compras","o","тележка","super"), ("caixa","a","касса","super"),
("prateleiras","as","полки","super"), ("talho","o","мясной отдел","super"),
("peixaria","a","рыбный отдел","super"), ("padaria","a","пекарня","super"),
("presunto","o","хамон, ветчина","super"), ("queijo","o","сыр","super"),
("iogurte","o","йогурт","super"), ("manteiga","a","сливочное масло","super"),
("ovos","os","яйца","super"), ("arroz","o","рис","super"),
("massa","a","макароны","super"), ("azeite","o","оливковое масло","super"),
("vinho","o","вино","super"), ("sumo","o","сок","super"),
("pagar em dinheiro",None,"платить наличными","super"),
("pagar com cartão de crédito",None,"платить картой","super"),
("pagar com cheque",None,"платить чеком","super"),
# ---------- restaurante ----------
("ementa","a","меню","rest2"), ("empregado de mesa","o","официант","rest2"),
("entrada","a","закуска","rest2"), ("prato principal","o","основное блюдо","rest2"),
("sobremesas","as","десерты","rest2"), ("conta","a","счёт","rest2"),
("gorjeta","a","чаевые","rest2"), ("peixe","o","рыба","rest2"),
("carne","a","мясо","rest2"), ("sopa","a","суп","rest2"),
("salada","a","салат","rest2"), ("bebidas","as","напитки","rest2"),
# ---------- estação / aeroporto / porto ----------
("comboio","o","поезд","viagem2"), ("carruagens","as","вагоны","viagem2"),
("bilheteira","a","билетная касса","viagem2"), ("linha","a","путь, платформа","viagem2"),
("horário","o","расписание","viagem2"), ("mala","a","чемодан","viagem2"),
("avião","o","самолёт","viagem2"), ("pista","a","взлётная полоса","viagem2"),
("piloto","o","пилот","viagem2"), ("hospedeira de bordo","a","стюардесса","viagem2"),
("passaporte","o","паспорт","viagem2"), ("bagagem","a","багаж","viagem2"),
("porto","o","порт","viagem2"), ("barco","o","корабль, лодка","viagem2"),
("farol","o","маяк","viagem2"), ("gaivota","a","чайка","viagem2"),
("bandeira","a","флаг","viagem2"), ("âncora","a","якорь","viagem2"),
# ---------- parque / lazer ----------
("baloiço","o","качели","parque2"), ("escorrega (do parque)","o","горка","parque2"),
("banco de jardim","o","скамейка","parque2"), ("lago","o","пруд","parque2"),
("patos","os","утки","parque2"), ("andar de bicicleta",None,"кататься на велосипеде","parque2"),
("passear o cão",None,"выгуливать собаку","parque2"),
("fazer um piquenique",None,"устроить пикник","parque2"),
("correr",None,"бегать","parque2"), ("saltar",None,"прыгать","parque2"),
# ---------- ações ----------
("empurrar",None,"толкать","acoes"), ("cair",None,"падать","acoes"),
("chorar",None,"плакать","acoes"), ("rir",None,"смеяться","acoes"),
("conduzir",None,"водить машину","acoes"), ("guiar",None,"вести, управлять","acoes"),
("estudar",None,"учиться","acoes"), ("cozinhar",None,"готовить","acoes"),
("limpar o pó",None,"вытирать пыль","acoes"), ("pôr a mesa",None,"накрывать на стол","acoes"),
("lavar a roupa",None,"стирать","acoes"), ("pendurar a roupa",None,"вешать бельё","acoes"),
("despejar o lixo",None,"выбрасывать мусор","acoes"),
("cuidar das crianças",None,"присматривать за детьми","acoes"),
("decorar a casa",None,"украшать дом","acoes"),
("pregar um prego",None,"забивать гвоздь","acoes"),
("engraxar os sapatos",None,"чистить обувь","acoes"),
("caminhar",None,"ходить пешком","acoes"), ("sentar-se",None,"садиться","acoes"),
("entrar",None,"входить","acoes"), ("sair",None,"выходить","acoes"),
("abrir a porta",None,"открывать дверь","acoes"), ("fechar a porta",None,"закрывать дверь","acoes"),
("cumprimentar",None,"здороваться","acoes"), ("adormecer",None,"засыпать","acoes"),
# ---------- desporto ----------
("futebol","o","футбол","desporto2"), ("basquetebol","o","баскетбол","desporto2"),
("voleibol","o","волейбол","desporto2"), ("ténis (desporto)","o","теннис","desporto2"),
("ténis de mesa","o","настольный теннис","desporto2"), ("natação","a","плавание","desporto2"),
("ciclismo","o","велоспорт","desporto2"), ("atletismo","o","лёгкая атлетика","desporto2"),
("ginástica rítmica","a","художественная гимнастика","desporto2"),
("patinagem","a","катание на коньках","desporto2"),
("patinagem artística","a","фигурное катание","desporto2"),
("hóquei em patins","o","хоккей на роликах","desporto2"),
("hóquei sobre o gelo","o","хоккей на льду","desporto2"),
("esqui","o","лыжи","desporto2"), ("esqui aquático","o","водные лыжи","desporto2"),
("judo","o","дзюдо","desporto2"), ("karate","o","карате","desporto2"),
("kick-boxing","o","кикбоксинг","desporto2"), ("esgrima","a","фехтование","desporto2"),
("alpinismo","o","альпинизм","desporto2"), ("hipismo","o","конный спорт","desporto2"),
("remo","o","гребля","desporto2"), ("vela (desporto)","a","парусный спорт","desporto2"),
("golfe","o","гольф","desporto2"), ("halterofilismo","o","тяжёлая атлетика","desporto2"),
("tiro ao arco","o","стрельба из лука","desporto2"), ("xadrez","o","шахматы","desporto2"),
("jogo de damas","o","шашки","desporto2"), ("jogo de cartas","o","карточная игра","desporto2"),
("caça","a","охота","desporto2"), ("pesca","a","рыбалка","desporto2"),
("dança","a","танцы","desporto2"), ("marcha","a","спортивная ходьба","desporto2"),
("paraquedismo","o","парашютный спорт","desporto2"),
("automobilismo","o","автоспорт","desporto2"), ("badminton","o","бадминтон","desporto2"),
("skate","o","скейтборд","desporto2"), ("mergulhar",None,"нырять","desporto2"),
("ganhar",None,"выигрывать","desporto2"), ("vencer",None,"побеждать","desporto2"),
("chutar",None,"бить по мячу","desporto2"), ("lançar a bola",None,"бросать мяч","desporto2"),
("levantar pesos",None,"поднимать штангу","desporto2"),
# ---------- tempo / estações ----------
("primavera","a","весна","tempo2"), ("verão","o","лето","tempo2"),
("outono","o","осень","tempo2"), ("inverno","o","зима","tempo2"),
("tempestade","a","гроза, буря","tempo2"), ("trovoada","a","гром","tempo2"),
("chuva","a","дождь","tempo2"), ("neve","a","снег","tempo2"),
("gelo","o","лёд","tempo2"), ("geada","a","иней","tempo2"),
("nevoeiro","o","туман","tempo2"), ("neblina","a","дымка","tempo2"),
("nuvens","as","облака","tempo2"), ("vento","o","ветер","tempo2"),
("brisa","a","лёгкий ветерок","tempo2"), ("arco-íris","o","радуга","tempo2"),
("poças de água","as","лужи","tempo2"), ("boneco de neve","o","снеговик","tempo2"),
("bola de neve","a","снежок","tempo2"),
("está bom tempo",None,"хорошая погода","tempo2"),
("está mau tempo",None,"плохая погода","tempo2"),
("está calor",None,"жарко","tempo2"), ("está frio",None,"холодно","tempo2"),
("o céu está azul",None,"небо голубое","tempo2"),
# ---------- contrários ----------
("silencioso",None,"тихий","contrarios"), ("barulhento",None,"шумный","contrarios"),
("quente",None,"горячий","contrarios"), ("frio",None,"холодный","contrarios"),
("perto",None,"близко","contrarios"), ("longe",None,"далеко","contrarios"),
("triste",None,"грустный","contrarios"), ("contente",None,"довольный","contrarios"),
("cheio",None,"полный","contrarios"), ("vazio",None,"пустой","contrarios"),
("rápido",None,"быстрый","contrarios"), ("lento",None,"медленный","contrarios"),
("pesado",None,"тяжёлый","contrarios"), ("leve",None,"лёгкий","contrarios"),
("macio",None,"мягкий","contrarios"), ("áspero",None,"шершавый","contrarios"),
("bonita",None,"красивая","contrarios"), ("feia",None,"некрасивая","contrarios"),
("sábio",None,"мудрый","contrarios"), ("ignorante",None,"невежественный","contrarios"),
("graciosa",None,"изящная","contrarios"), ("desajeitada",None,"неуклюжая","contrarios"),
# ---------- cores e formas ----------
("vermelho",None,"красный","cores2"), ("amarelo",None,"жёлтый","cores2"),
("azul",None,"синий","cores2"), ("verde",None,"зелёный","cores2"),
("preto",None,"чёрный","cores2"), ("branco",None,"белый","cores2"),
("cinzento",None,"серый","cores2"), ("castanho",None,"коричневый","cores2"),
("roxo",None,"фиолетовый","cores2"), ("bege",None,"бежевый","cores2"),
("cor de rosa",None,"розовый","cores2"), ("cor de laranja",None,"оранжевый","cores2"),
("quadrado","o","квадрат","cores2"), ("triângulo","o","треугольник","cores2"),
("redondo",None,"круглый","cores2"), ("estrela","a","звезда","cores2"),
("cubo","o","куб","cores2"), ("esfera","a","сфера","cores2"),
("cone","o","конус","cores2"), ("cilindro","o","цилиндр","cores2"),
("pirâmide","a","пирамида","cores2"), ("hexágono","o","шестиугольник","cores2"),
# ---------- horas ----------
("relógio de pulso","o","наручные часы","horas2"),
("relógio digital","o","электронные часы","horas2"),
("despertador (relógio)","o","будильник","horas2"),
("ponteiros","os","стрелки часов","horas2"), ("segundos","os","секунды","horas2"),
("minutos","os","минуты","horas2"), ("horas","as","часы (время)","horas2"),
("meia hora","a","полчаса","horas2"), ("um quarto de hora","o","четверть часа","horas2"),
("três quartos de hora","os","три четверти часа","horas2"),
("chegar a horas",None,"прийти вовремя","horas2"),
("estar adiantado",None,"прийти раньше","horas2"),
("estar atrasado",None,"опаздывать","horas2"),
# ---------- festas ----------
("Dia dos Namorados","o","День святого Валентина","festas2"),
("namorado","o","парень, возлюбленный","festas2"),
("Santo António","o","праздник святого Антония","festas2"),
("São Pedro","o","праздник святого Петра","festas2"),
("festas populares","as","народные праздники","festas2"),
("caldo-verde","o","калду-верде (суп)","festas2"),
("farturas","as","фартуры (сладость)","festas2"),
]

THEMES2 = [
 ("corpo2",       "Тело — снаружи",        "🧍"),
 ("corpo_dentro", "Тело — внутри",         "🫀"),
 ("saude2",       "Здоровье и болезни",    "🤒"),
 ("roupa2",       "Одежда женская",        "👗"),
 ("roupa_homem",  "Одежда мужская",        "👔"),
 ("rotina",       "Распорядок дня",        "⏰"),
 ("familia2",     "Семья и родственники",  "👨‍👩‍👧"),
 ("casa2",        "Дом и комнаты",         "🏠"),
 ("sala",         "Гостиная",              "🛋"),
 ("jantar",       "Столовая и сервировка", "🍽"),
 ("cozinha2",     "Кухня и уборка",        "🍳"),
 ("quarto2",      "Спальня",               "🛏"),
 ("banho",        "Ванная",                "🛁"),
 ("escritorio",   "Кабинет и канцелярия",  "🖊"),
 ("jardim",       "Сад и растения",        "🌳"),
 ("cidade2",      "Город и направления",   "🏙"),
 ("lugar2",       "Предлоги места",        "📍"),
 ("escola2",      "Школа и работа",        "🎒"),
 ("oficina",      "Автомастерская, транспорт","🚗"),
 ("super",        "Супермаркет и продукты","🛒"),
 ("rest2",        "Ресторан",              "🍷"),
 ("viagem2",      "Вокзал, аэропорт, порт","✈️"),
 ("parque2",      "Парк и отдых",          "🌲"),
 ("acoes",        "Действия и жесты",      "🤹"),
 ("desporto2",    "Спорт и игры",          "⚽"),
 ("tempo2",       "Погода и времена года", "⛅"),
 ("contrarios",   "Противоположности",     "↔️"),
 ("cores2",       "Цвета и формы",         "🎨"),
 ("horas2",       "Время и часы",          "🕐"),
 ("festas2",      "Народные праздники",    "🎉"),
]
