# -*- coding: utf-8 -*-
"""Лексика Português a Valer 1 (A1). Формат: (pt, артикль|None, ru, юнит, тема)."""

VOCAB = [
# --- U1: приветствия и знакомство ---
("olá", None, "привет", 1, "apresentação"),
("bom dia", None, "доброе утро / добрый день", 1, "apresentação"),
("boa tarde", None, "добрый день (после обеда)", 1, "apresentação"),
("boa noite", None, "добрый вечер / спокойной ночи", 1, "apresentação"),
("adeus", None, "до свидания", 1, "apresentação"),
("até logo", None, "до скорого", 1, "apresentação"),
("muito prazer", None, "очень приятно", 1, "apresentação"),
("igualmente", None, "взаимно", 1, "apresentação"),
("obrigada", None, "спасибо (говорит женщина)", 1, "apresentação"),
("obrigado", None, "спасибо (говорит мужчина)", 1, "apresentação"),
("desculpe", None, "извините (формально)", 1, "apresentação"),
("por favor", None, "пожалуйста (просьба)", 1, "apresentação"),
("nome", "o", "имя", 1, "apresentação"),
("apelido", "o", "фамилия", 1, "apresentação"),
("idade", "a", "возраст", 1, "apresentação"),
("morada", "a", "адрес", 1, "apresentação"),
("nacionalidade", "a", "гражданство, национальность", 1, "apresentação"),
("país", "o", "страна", 1, "apresentação"),
("cidade", "a", "город", 1, "apresentação"),
("rua", "a", "улица", 1, "apresentação"),
# nacionalidades
("português", None, "португальский / португалец", 1, "nacionalidades"),
("espanhol", None, "испанский / испанец", 1, "nacionalidades"),
("francês", None, "французский / француз", 1, "nacionalidades"),
("inglês", None, "английский / англичанин", 1, "nacionalidades"),
("alemão", None, "немецкий / немец", 1, "nacionalidades"),
("italiano", None, "итальянский / итальянец", 1, "nacionalidades"),
("brasileiro", None, "бразильский / бразилец", 1, "nacionalidades"),
("russo", None, "русский", 1, "nacionalidades"),
("chinês", None, "китайский / китаец", 1, "nacionalidades"),
("sueco", None, "шведский / швед", 1, "nacionalidades"),
("suíço", None, "швейцарский / швейцарец", 1, "nacionalidades"),
("polaco", None, "польский / поляк", 1, "nacionalidades"),
("grego", None, "греческий / грек", 1, "nacionalidades"),
("croata", None, "хорватский / хорват", 1, "nacionalidades"),
("ucraniano", None, "украинский / украинец", 1, "nacionalidades"),
("cabo-verdiano", None, "кабо-вердианский", 1, "nacionalidades"),
("angolano", None, "ангольский", 1, "nacionalidades"),
("belga", None, "бельгийский / бельгиец", 1, "nacionalidades"),
# profissões
("professor", "o", "преподаватель", 1, "profissões"),
("médico", "o", "врач", 1, "profissões"),
("enfermeiro", "o", "медбрат, медсестра", 1, "profissões"),
("advogado", "o", "адвокат", 1, "profissões"),
("engenheiro", "o", "инженер", 1, "profissões"),
("ator", "o", "актёр", 1, "profissões"),
("cantor", "o", "певец", 1, "profissões"),
("escritor", "o", "писатель", 1, "profissões"),
("pintor", "o", "художник, маляр", 1, "profissões"),
("bailarino", "o", "танцор", 1, "profissões"),
("cabeleireiro", "o", "парикмахер", 1, "profissões"),
("mecânico", "o", "механик", 1, "profissões"),
("motorista", "o", "водитель", 1, "profissões"),
("polícia", "o", "полицейский", 1, "profissões"),
("rececionista", "o", "администратор на ресепшене", 1, "profissões"),
("hospedeira", "a", "стюардесса", 1, "profissões"),
("empregado de balcão", "o", "продавец за стойкой, бариста", 1, "profissões"),
("jornalista", "o", "журналист", 1, "profissões"),
("veterinário", "o", "ветеринар", 1, "profissões"),
("diretor", "o", "директор", 1, "profissões"),
("estudante", "o", "студент", 1, "profissões"),
("informático", "o", "айтишник", 1, "profissões"),
("tenista", "o", "теннисист", 1, "profissões"),
("arquiteto", "o", "архитектор", 1, "profissões"),
# --- U2: семья, характер, место ---
("pai", "o", "отец", 2, "família"),
("mãe", "a", "мать", 2, "família"),
("filho", "o", "сын", 2, "família"),
("filha", "a", "дочь", 2, "família"),
("irmão", "o", "брат", 2, "família"),
("irmã", "a", "сестра", 2, "família"),
("avô", "o", "дедушка", 2, "família"),
("avó", "a", "бабушка", 2, "família"),
("neto", "o", "внук", 2, "família"),
("tio", "o", "дядя", 2, "família"),
("tia", "a", "тётя", 2, "família"),
("primo", "o", "двоюродный брат", 2, "família"),
("sobrinho", "o", "племянник", 2, "família"),
("marido", "o", "муж", 2, "família"),
("mulher", "a", "жена, женщина", 2, "família"),
("namorado", "o", "парень, бойфренд", 2, "família"),
("pais", "os", "родители", 2, "família"),
("filhos", "os", "дети", 2, "família"),
("amigo", "o", "друг", 2, "família"),
("colega", "o", "коллега, однокурсник", 2, "família"),
("vizinho", "o", "сосед", 2, "família"),
("simpático", None, "приятный, милый", 2, "carácter"),
("antipático", None, "неприятный", 2, "carácter"),
("divertido", None, "весёлый, забавный", 2, "carácter"),
("alegre", None, "радостный", 2, "carácter"),
("tímido", None, "застенчивый", 2, "carácter"),
("sociável", None, "общительный", 2, "carácter"),
("comunicativo", None, "общительный, разговорчивый", 2, "carácter"),
("trabalhador", None, "трудолюбивый", 2, "carácter"),
("simples", None, "простой", 2, "carácter"),
("elegante", None, "элегантный", 2, "carácter"),
("bonito", None, "красивый", 2, "carácter"),
("velho", None, "старый", 2, "carácter"),
("novo", None, "новый, молодой", 2, "carácter"),
("dentro de", None, "внутри", 2, "lugar"),
("ao lado de", None, "рядом с", 2, "lugar"),
("em frente de", None, "напротив", 2, "lugar"),
("atrás de", None, "позади, за", 2, "lugar"),
("debaixo de", None, "под", 2, "lugar"),
("em cima de", None, "на, сверху", 2, "lugar"),
("entre", None, "между", 2, "lugar"),
("perto de", None, "близко к", 2, "lugar"),
("longe de", None, "далеко от", 2, "lugar"),
("mesa", "a", "стол", 2, "objetos"),
("cadeira", "a", "стул", 2, "objetos"),
("janela", "a", "окно", 2, "objetos"),
("porta", "a", "дверь", 2, "objetos"),
("estante", "a", "стеллаж, книжная полка", 2, "objetos"),
("mochila", "a", "рюкзак", 2, "objetos"),
("estojo", "o", "пенал", 2, "objetos"),
("caderno", "o", "тетрадь", 2, "objetos"),
("livro", "o", "книга", 2, "objetos"),
("telemóvel", "o", "мобильный телефон", 2, "objetos"),
("computador", "o", "компьютер", 2, "objetos"),
("mala", "a", "чемодан, сумка", 2, "objetos"),
("óculos", "os", "очки", 2, "objetos"),
("chave", "a", "ключ", 2, "objetos"),
# --- U3: еда, ресторан, время ---
("pequeno-almoço", "o", "завтрак", 3, "refeições"),
("almoço", "o", "обед", 3, "refeições"),
("jantar", "o", "ужин", 3, "refeições"),
("lanche", "o", "полдник, перекус", 3, "refeições"),
("sobremesa", "a", "десерт", 3, "refeições"),
("entrada", "a", "закуска", 3, "refeições"),
("prato do dia", "o", "блюдо дня", 3, "restaurante"),
("ementa", "a", "меню", 3, "restaurante"),
("conta", "a", "счёт", 3, "restaurante"),
("empregado", "o", "официант", 3, "restaurante"),
("esplanada", "a", "терраса кафе", 3, "restaurante"),
("carne", "a", "мясо", 3, "alimentação"),
("peixe", "o", "рыба", 3, "alimentação"),
("frango", "o", "курица", 3, "alimentação"),
("bife", "o", "стейк", 3, "alimentação"),
("costeleta", "a", "отбивная", 3, "alimentação"),
("bacalhau", "o", "треска", 3, "alimentação"),
("sardinha", "a", "сардина", 3, "alimentação"),
("salmão", "o", "лосось", 3, "alimentação"),
("arroz", "o", "рис", 3, "alimentação"),
("massa", "a", "паста, макароны", 3, "alimentação"),
("pão", "o", "хлеб", 3, "alimentação"),
("sopa", "a", "суп", 3, "alimentação"),
("queijo", "o", "сыр", 3, "alimentação"),
("manteiga", "a", "масло сливочное", 3, "alimentação"),
("iogurte", "o", "йогурт", 3, "alimentação"),
("leite", "o", "молоко", 3, "alimentação"),
("ovo", "o", "яйцо", 3, "alimentação"),
("alface", "a", "салат (листовой)", 3, "alimentação"),
("cenoura", "a", "морковь", 3, "alimentação"),
("cebola", "a", "лук", 3, "alimentação"),
("tomate", "o", "помидор", 3, "alimentação"),
("batata", "a", "картофель", 3, "alimentação"),
("legumes", "os", "овощи", 3, "alimentação"),
("fruta", "a", "фрукты", 3, "alimentação"),
("banana", "a", "банан", 3, "alimentação"),
("laranja", "a", "апельсин", 3, "alimentação"),
("água", "a", "вода", 3, "bebidas"),
("vinho", "o", "вино", 3, "bebidas"),
("cerveja", "a", "пиво", 3, "bebidas"),
("café", "o", "кофе", 3, "bebidas"),
("chá", "o", "чай", 3, "bebidas"),
("sumo", "o", "сок", 3, "bebidas"),
("bolo", "o", "торт, пирожное", 3, "doces"),
("pastel de nata", "o", "пирожное «паштел де ната»", 3, "doces"),
("biscoito", "o", "печенье", 3, "doces"),
("gelado", "o", "мороженое", 3, "doces"),
("chocolate", "o", "шоколад", 3, "doces"),
("açúcar", "o", "сахар", 3, "doces"),
("sempre", None, "всегда", 3, "frequência"),
("nunca", None, "никогда", 3, "frequência"),
("às vezes", None, "иногда", 3, "frequência"),
("muitas vezes", None, "часто", 3, "frequência"),
("raramente", None, "редко", 3, "frequência"),
("frequentemente", None, "часто, регулярно", 3, "frequência"),
("todos os dias", None, "каждый день", 3, "frequência"),
("hora", "a", "час", 3, "horas"),
("meia-noite", "a", "полночь", 3, "horas"),
("meio-dia", "o", "полдень", 3, "horas"),
("manhã", "a", "утро", 3, "horas"),
("tarde", "a", "вторая половина дня", 3, "horas"),
("noite", "a", "вечер, ночь", 3, "horas"),
# --- U4: дом, город, транспорт ---
("casa", "a", "дом", 4, "casa"),
("apartamento", "o", "квартира", 4, "casa"),
("quarto", "o", "комната, спальня", 4, "casa"),
("sala", "a", "гостиная", 4, "casa"),
("cozinha", "a", "кухня", 4, "casa"),
("casa de banho", "a", "ванная, туалет", 4, "casa"),
("varanda", "a", "балкон", 4, "casa"),
("escritório", "o", "кабинет, офис", 4, "casa"),
("andar", "o", "этаж", 4, "casa"),
("elevador", "o", "лифт", 4, "casa"),
("prédio", "o", "жилой дом, здание", 4, "casa"),
("frigorífico", "o", "холодильник", 4, "casa"),
("armário", "o", "шкаф", 4, "casa"),
("gaveta", "a", "ящик (стола)", 4, "casa"),
("hospital", "o", "больница", 4, "cidade"),
("farmácia", "a", "аптека", 4, "cidade"),
("escola", "a", "школа", 4, "cidade"),
("biblioteca", "a", "библиотека", 4, "cidade"),
("cinema", "o", "кинотеатр", 4, "cidade"),
("museu", "o", "музей", 4, "cidade"),
("banco", "o", "банк", 4, "cidade"),
("mercearia", "a", "продуктовая лавка", 4, "cidade"),
("supermercado", "o", "супермаркет", 4, "cidade"),
("padaria", "a", "булочная", 4, "cidade"),
("pastelaria", "a", "кондитерская, кафе", 4, "cidade"),
("talho", "o", "мясная лавка", 4, "cidade"),
("frutaria", "a", "фруктовая лавка", 4, "cidade"),
("livraria", "a", "книжный магазин", 4, "cidade"),
("quiosque", "o", "киоск", 4, "cidade"),
("hotel", "o", "отель", 4, "cidade"),
("estação de correios", "a", "почта", 4, "cidade"),
("jardim", "o", "сад, парк", 4, "cidade"),
("praça", "a", "площадь", 4, "cidade"),
("avenida", "a", "проспект", 4, "cidade"),
("passadeira", "a", "пешеходный переход", 4, "direções"),
("à esquerda", None, "налево", 4, "direções"),
("à direita", None, "направо", 4, "direções"),
("em frente", None, "прямо", 4, "direções"),
("primeira rua", "a", "первая улица", 4, "direções"),
("perto", None, "близко", 4, "direções"),
("longe", None, "далеко", 4, "direções"),
("carro", "o", "машина", 4, "transportes"),
("autocarro", "o", "автобус", 4, "transportes"),
("metro", "o", "метро", 4, "transportes"),
("comboio", "o", "поезд", 4, "transportes"),
("elétrico", "o", "трамвай", 4, "transportes"),
("bicicleta", "a", "велосипед", 4, "transportes"),
("mota", "a", "мотоцикл", 4, "transportes"),
("avião", "o", "самолёт", 4, "transportes"),
("barco", "o", "лодка, корабль", 4, "transportes"),
("táxi", "o", "такси", 4, "transportes"),
("a pé", None, "пешком", 4, "transportes"),
("paragem", "a", "остановка", 4, "transportes"),
("bilhete", "o", "билет", 4, "transportes"),
# --- U5: погода, месяцы, одежда ---
("janeiro", None, "январь", 5, "meses"),
("fevereiro", None, "февраль", 5, "meses"),
("março", None, "март", 5, "meses"),
("abril", None, "апрель", 5, "meses"),
("maio", None, "май", 5, "meses"),
("junho", None, "июнь", 5, "meses"),
("julho", None, "июль", 5, "meses"),
("agosto", None, "август", 5, "meses"),
("setembro", None, "сентябрь", 5, "meses"),
("outubro", None, "октябрь", 5, "meses"),
("novembro", None, "ноябрь", 5, "meses"),
("dezembro", None, "декабрь", 5, "meses"),
("primavera", "a", "весна", 5, "estações"),
("verão", "o", "лето", 5, "estações"),
("outono", "o", "осень", 5, "estações"),
("inverno", "o", "зима", 5, "estações"),
("sol", "o", "солнце", 5, "tempo"),
("chuva", "a", "дождь", 5, "tempo"),
("neve", "a", "снег", 5, "tempo"),
("vento", "o", "ветер", 5, "tempo"),
("nevoeiro", "o", "туман", 5, "tempo"),
("nuvem", "a", "облако", 5, "tempo"),
("calor", "o", "жара", 5, "tempo"),
("frio", "o", "холод", 5, "tempo"),
("casaco", "o", "куртка, пальто", 5, "roupa"),
("camisola", "a", "свитер, футболка", 5, "roupa"),
("camisa", "a", "рубашка", 5, "roupa"),
("calças", "as", "брюки", 5, "roupa"),
("calções", "os", "шорты", 5, "roupa"),
("vestido", "o", "платье", 5, "roupa"),
("saia", "a", "юбка", 5, "roupa"),
("sapato", "o", "туфля", 5, "roupa"),
("ténis", "os", "кроссовки", 5, "roupa"),
("sandália", "a", "сандалия", 5, "roupa"),
("bota", "a", "сапог, ботинок", 5, "roupa"),
("gorro", "o", "шапка", 5, "roupa"),
("boné", "o", "кепка", 5, "roupa"),
("cachecol", "o", "шарф", 5, "roupa"),
("biquíni", "o", "бикини", 5, "roupa"),
("gabardina", "a", "плащ", 5, "roupa"),
# --- U6: тело и здоровье ---
("cabeça", "a", "голова", 6, "corpo"),
("olho", "o", "глаз", 6, "corpo"),
("boca", "a", "рот", 6, "corpo"),
("nariz", "o", "нос", 6, "corpo"),
("orelha", "a", "ухо", 6, "corpo"),
("dente", "o", "зуб", 6, "corpo"),
("garganta", "a", "горло", 6, "corpo"),
("braço", "o", "рука (от плеча)", 6, "corpo"),
("mão", "a", "кисть руки", 6, "corpo"),
("perna", "a", "нога", 6, "corpo"),
("pé", "o", "ступня", 6, "corpo"),
("joelho", "o", "колено", 6, "corpo"),
("costas", "as", "спина", 6, "corpo"),
("barriga", "a", "живот", 6, "corpo"),
("peito", "o", "грудь", 6, "corpo"),
("cabelo", "o", "волосы", 6, "corpo"),
("coração", "o", "сердце", 6, "corpo"),
("dor", "a", "боль", 6, "saúde"),
("febre", "a", "температура, жар", 6, "saúde"),
("tosse", "a", "кашель", 6, "saúde"),
("gripe", "a", "грипп", 6, "saúde"),
("insónia", "a", "бессонница", 6, "saúde"),
("cansaço", "o", "усталость", 6, "saúde"),
("infeção", "a", "инфекция", 6, "saúde"),
("alergia", "a", "аллергия", 6, "saúde"),
("comprimido", "o", "таблетка", 6, "saúde"),
("analgésico", "o", "обезболивающее", 6, "saúde"),
("antibiótico", "o", "антибиотик", 6, "saúde"),
("receita", "a", "рецепт", 6, "saúde"),
("análises", "as", "анализы", 6, "saúde"),
("doente", None, "больной", 6, "saúde"),
("cansado", None, "усталый", 6, "saúde"),
("nervoso", None, "нервный, на взводе", 6, "saúde"),
("saudável", None, "здоровый, полезный", 6, "saúde"),
("melhoras", "as", "выздоровление («поправляйтесь»)", 6, "saúde"),
# --- U7: праздники ---
("aniversário", "o", "день рождения", 7, "festas"),
("festa", "a", "праздник, вечеринка", 7, "festas"),
("casamento", "o", "свадьба", 7, "festas"),
("Natal", "o", "Рождество", 7, "festas"),
("Páscoa", "a", "Пасха", 7, "festas"),
("Carnaval", "o", "карнавал", 7, "festas"),
("Ano Novo", "o", "Новый год", 7, "festas"),
("feriado", "o", "выходной, праздничный день", 7, "festas"),
("presente", "o", "подарок", 7, "festas"),
("convite", "o", "приглашение", 7, "festas"),
("convidado", "o", "гость", 7, "festas"),
("disfarce", "o", "костюм (карнавальный)", 7, "festas"),
("árvore", "a", "дерево, ёлка", 7, "festas"),
("presépio", "o", "рождественский вертеп", 7, "festas"),
("bolo-rei", "o", "рождественский кекс", 7, "festas"),
("parabéns", "os", "поздравления", 7, "festas"),
("faca", "a", "нож", 7, "mesa"),
("garfo", "o", "вилка", 7, "mesa"),
("colher", "a", "ложка", 7, "mesa"),
("copo", "o", "стакан", 7, "mesa"),
("prato", "o", "тарелка, блюдо", 7, "mesa"),
("guardanapo", "o", "салфетка", 7, "mesa"),
("garrafa", "a", "бутылка", 7, "mesa"),
("toalha", "a", "скатерть, полотенце", 7, "mesa"),
# --- U8: отпуск и путешествия ---
("férias", "as", "отпуск, каникулы", 8, "viagens"),
("viagem", "a", "поездка", 8, "viagens"),
("praia", "a", "пляж", 8, "viagens"),
("montanha", "a", "гора", 8, "viagens"),
("mar", "o", "море", 8, "viagens"),
("ilha", "a", "остров", 8, "viagens"),
("aeroporto", "o", "аэропорт", 8, "viagens"),
("passaporte", "o", "паспорт", 8, "viagens"),
("voo", "o", "рейс", 8, "viagens"),
("destino", "o", "направление, пункт назначения", 8, "viagens"),
("monumento", "o", "памятник", 8, "viagens"),
("mercado", "o", "рынок", 8, "viagens"),
("caminhada", "a", "прогулка пешком, поход", 8, "tempos livres"),
("mergulho", "o", "дайвинг", 8, "tempos livres"),
("escalada", "a", "скалолазание", 8, "tempos livres"),
("esqui", "o", "лыжи", 8, "tempos livres"),
("campismo", "o", "кемпинг", 8, "tempos livres"),
("piquenique", "o", "пикник", 8, "tempos livres"),
("passeio", "o", "прогулка", 8, "tempos livres"),
("ontem", None, "вчера", 8, "marcadores"),
("hoje", None, "сегодня", 8, "marcadores"),
("amanhã", None, "завтра", 8, "marcadores"),
("na semana passada", None, "на прошлой неделе", 8, "marcadores"),
("no mês passado", None, "в прошлом месяце", 8, "marcadores"),
("no ano passado", None, "в прошлом году", 8, "marcadores"),
("já", None, "уже", 8, "marcadores"),
("ainda não", None, "ещё не", 8, "marcadores"),
]
